const FIX_VALUES = {
  "1": {
    "B": "BUY",
    "S": "SELL",
    "T": "TRADE",
    "X": "CROSS"
  },
  "5": {
    "C": "CANCEL",
    "N": "NEW",
    "R": "REPLACE"
  },
  "6": {
    "1": "PER_UNIT",
    "2": "PERCENT",
    "3": "ABSOLUTE",
    "4": "PERCENTAGE_WAIVED_4",
    "5": "PERCENTAGE_WAIVED_5",
    "6": "POINTS_PER_BOND_OR_CONTRACT"
  },
  "14": {
    "0": "STAY_ON_OFFER_SIDE",
    "1": "NOT_HELD",
    "2": "WORK",
    "3": "GO_ALONG",
    "4": "OVER_THE_DAY",
    "5": "HELD",
    "6": "PARTICIPANT_DONT_INITIATE",
    "7": "STRICT_SCALE",
    "8": "TRY_TO_SCALE",
    "9": "STAY_ON_BID_SIDE",
    "A": "NO_CROSS",
    "a": "TRAILING_STOP_PEG",
    "B": "OK_TO_CROSS",
    "b": "STRICT_LIMIT",
    "c": "IGNORE_PRICE_VALIDITY_CHECKS",
    "C": "CALL_FIRST",
    "d": "PEG_TO_LIMIT_PRICE",
    "D": "PERCENT_OF_VOLUME",
    "E": "DO_NOT_INCREASE",
    "e": "WORK_TO_TARGET_STRATEGY",
    "F": "DO_NOT_REDUCE",
    "G": "ALL_OR_NONE",
    "H": "REINSTATE_ON_SYSTEM_FAILURE",
    "I": "INSTITUTIONS_ONLY",
    "J": "REINSTATE_ON_TRADING_HALT",
    "K": "CANCEL_ON_TRADING_HALT",
    "L": "LAST_PEG",
    "M": "MID_PRICE_PEG",
    "N": "NON_NEGOTIABLE",
    "O": "OPENING_PEG",
    "P": "MARKET_PEG",
    "Q": "CANCEL_ON_SYSTEM_FAILURE",
    "R": "PRIMARY_PEG",
    "S": "SUSPEND",
    "U": "CUSTOMER_DISPLAY_INSTRUCTION",
    "V": "NETTING",
    "W": "PEG_TO_VWAP",
    "X": "TRADE_ALONG",
    "Y": "TRY_TO_STOP",
    "Z": "CANCEL_IF_NOT_BEST",
    "f": "INTERMARKET_SWEEP",
    "j": "SINGLE_EXECUTION_REQUESTED_FOR_BLOCK_TRADE",
    "g": "EXTERNAL_ROUTING_ALLOWED",
    "h": "EXTERNAL_ROUTING_NOT_ALLOWED",
    "i": "IMBALANCE_ONLY",
    "T": "FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER",
    "k": "BEST_EXECUTION",
    "l": "SUSPEND_ON_SYSTEM_FAILURE",
    "m": "SUSPEND_ON_TRADING_HALT",
    "n": "REINSTATE_ON_CONNECTION_LOSS",
    "o": "CANCEL_ON_CONNECTION_LOSS",
    "p": "SUSPEND_ON_CONNECTION_LOSS",
    "q": "RELEASE_FROM_SUSPENSION",
    "r": "EXECUTE_AS_DELTA_NEUTRAL_USING_VOLATILITY_PROVIDED",
    "s": "EXECUTE_AS_DURATION_NEUTRAL",
    "t": "EXECUTE_AS_FX_NEUTRAL"
  },
  "19": {
    "0": "NEW",
    "1": "CANCEL",
    "2": "CORRECT",
    "3": "STATUS"
  },
  "21": {
    "1": "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION",
    "2": "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK",
    "3": "MANUAL_ORDER_BEST_EXECUTION"
  },
  "22": {
    "1": "CUSIP",
    "2": "SEDOL",
    "3": "QUIK",
    "4": "ISIN_NUMBER",
    "5": "RIC_CODE",
    "6": "ISO_CURRENCY_CODE",
    "7": "ISO_COUNTRY_CODE",
    "8": "EXCHANGE_SYMBOL",
    "9": "CONSOLIDATED_TAPE_ASSOCIATION",
    "A": "BLOOMBERG_SYMBOL",
    "B": "WERTPAPIER",
    "C": "DUTCH",
    "D": "VALOREN",
    "E": "SICOVAM",
    "F": "BELGIAN",
    "G": "COMMON",
    "H": "CLEARING_HOUSE",
    "I": "ISDA_FPML_PRODUCT_SPECIFICATION",
    "J": "OPTION_PRICE_REPORTING_AUTHORITY",
    "L": "LETTER_OF_CREDIT",
    "K": "ISDA_FPML_PRODUCT_URL",
    "M": "MARKETPLACE_ASSIGNED_IDENTIFIER"
  },
  "23": {
    "H": "HIGH",
    "L": "LOW",
    "M": "MEDIUM"
  },
  "26": {
    "0": "1000000000",
    "S": "SMALL",
    "M": "MEDIUM",
    "L": "LARGE",
    "U": "UNDISCLOSED_QUANTITY"
  },
  "28": {
    "C": "CANCEL",
    "N": "NEW",
    "R": "REPLACE"
  },
  "29": {
    "1": "AGENT",
    "2": "CROSS_AS_AGENT",
    "3": "CROSS_AS_PRINCIPAL",
    "4": "PRINCIPAL"
  },
  "30": {
    "0": "HEARTBEAT",
    "1": "TESTREQUEST",
    "2": "RESENDREQUEST",
    "3": "REJECT",
    "4": "SEQUENCERESET",
    "5": "LOGOUT",
    "6": "IOI",
    "7": "ADVERTISEMENT",
    "8": "EXECUTIONREPORT",
    "9": "ORDERCANCELREJECT",
    "A": "LOGON",
    "AA": "DERIVATIVESECURITYLIST",
    "AB": "NEWORDERMULTILEG",
    "AC": "MULTILEGORDERCANCELREPLACE",
    "AD": "TRADECAPTUREREPORTREQUEST",
    "AE": "TRADECAPTUREREPORT",
    "AF": "ORDERMASSSTATUSREQUEST",
    "AG": "QUOTEREQUESTREJECT",
    "AH": "RFQREQUEST",
    "AI": "QUOTESTATUSREPORT",
    "AJ": "QUOTERESPONSE",
    "AK": "CONFIRMATION",
    "AL": "POSITIONMAINTENANCEREQUEST",
    "AM": "POSITIONMAINTENANCEREPORT",
    "AN": "REQUESTFORPOSITIONS",
    "AO": "REQUESTFORPOSITIONSACK",
    "AP": "POSITIONREPORT",
    "AQ": "TRADECAPTUREREPORTREQUESTACK",
    "AR": "TRADECAPTUREREPORTACK",
    "AS": "ALLOCATIONREPORT",
    "AT": "ALLOCATIONREPORTACK",
    "AU": "CONFIRMATION_ACK",
    "AV": "SETTLEMENTINSTRUCTIONREQUEST",
    "AW": "ASSIGNMENTREPORT",
    "AX": "COLLATERALREQUEST",
    "AY": "COLLATERALASSIGNMENT",
    "AZ": "COLLATERALRESPONSE",
    "B": "NEWS",
    "BA": "COLLATERALREPORT",
    "BB": "COLLATERALINQUIRY",
    "BC": "NETWORKCOUNTERPARTYSYSTEMSTATUSREQUEST",
    "BD": "NETWORKCOUNTERPARTYSYSTEMSTATUSRESPONSE",
    "BE": "USERREQUEST",
    "BF": "USERRESPONSE",
    "BG": "COLLATERALINQUIRYACK",
    "BH": "CONFIRMATIONREQUEST",
    "BI": "TRADINGSESSIONLISTREQUEST",
    "BJ": "TRADINGSESSIONLIST",
    "BK": "SECURITYLISTUPDATEREPORT",
    "BL": "ADJUSTEDPOSITIONREPORT",
    "BM": "ALLOCATIONINSTRUCTIONALERT",
    "BN": "EXECUTIONACKNOWLEDGEMENT",
    "BO": "CONTRARYINTENTIONREPORT",
    "BP": "SECURITYDEFINITIONUPDATEREPORT",
    "BQ": "SETTLEMENTOBLIGATIONREPORT",
    "BR": "DERIVATIVESECURITYLISTUPDATEREPORT",
    "BS": "TRADINGSESSIONLISTUPDATEREPORT",
    "BT": "MARKETDEFINITIONREQUEST",
    "BU": "MARKETDEFINITION",
    "BV": "MARKETDEFINITIONUPDATEREPORT",
    "BW": "APPLICATIONMESSAGEREQUEST",
    "BX": "APPLICATIONMESSAGEREQUESTACK",
    "BY": "APPLICATIONMESSAGEREPORT",
    "BZ": "ORDERMASSACTIONREPORT",
    "C": "EMAIL",
    "CA": "ORDERMASSACTIONREQUEST",
    "CB": "USERNOTIFICATION",
    "CC": "STREAMASSIGNMENTREQUEST",
    "CD": "STREAMASSIGNMENTREPORT",
    "CE": "STREAMASSIGNMENTREPORTACK",
    "CF": "PARTYDETAILSLISTREQUEST",
    "CG": "PARTYDETAILSLISTREPORT",
    "D": "NEWORDERSINGLE",
    "E": "NEWORDERLIST",
    "F": "ORDERCANCELREQUEST",
    "G": "ORDERCANCELREPLACEREQUEST",
    "H": "ORDERSTATUSREQUEST",
    "J": "ALLOCATIONINSTRUCTION",
    "K": "LISTCANCELREQUEST",
    "L": "LISTEXECUTE",
    "M": "LISTSTATUSREQUEST",
    "N": "LISTSTATUS",
    "P": "ALLOCATIONINSTRUCTIONACK",
    "Q": "DONTKNOWTRADEDK",
    "R": "QUOTEREQUEST",
    "S": "QUOTE",
    "T": "SETTLEMENTINSTRUCTIONS",
    "V": "MARKETDATAREQUEST",
    "W": "MARKETDATASNAPSHOTFULLREFRESH",
    "X": "MARKETDATAINCREMENTALREFRESH",
    "Y": "MARKETDATAREQUESTREJECT",
    "Z": "QUOTECANCEL",
    "a": "QUOTESTATUSREQUEST",
    "b": "MASSQUOTEACKNOWLEDGEMENT",
    "c": "SECURITYDEFINITIONREQUEST",
    "d": "SECURITYDEFINITION",
    "e": "SECURITYSTATUSREQUEST",
    "f": "SECURITYSTATUS",
    "g": "TRADINGSESSIONSTATUSREQUEST",
    "h": "TRADINGSESSIONSTATUS",
    "i": "MASSQUOTE",
    "j": "BUSINESSMESSAGEREJECT",
    "k": "BIDREQUEST",
    "l": "BIDRESPONSE",
    "m": "LISTSTRIKEPRICE",
    "n": "XML_NON_FIX",
    "o": "REGISTRATIONINSTRUCTIONS",
    "p": "REGISTRATIONINSTRUCTIONSRESPONSE",
    "q": "ORDERMASSCANCELREQUEST",
    "r": "ORDERMASSCANCELREPORT",
    "s": "NEWORDERCROSS",
    "t": "CROSSORDERCANCELREPLACEREQUEST",
    "u": "CROSSORDERCANCELREQUEST",
    "v": "SECURITYTYPEREQUEST",
    "w": "SECURITYTYPES",
    "x": "SECURITYLISTREQUEST",
    "y": "SECURITYLIST",
    "z": "DERIVATIVESECURITYLISTREQUEST"
  },
  "36": {
    "0": "NEW",
    "1": "PARTIALLY_FILLED",
    "2": "FILLED",
    "3": "DONE_FOR_DAY",
    "4": "CANCELED",
    "5": "REPLACED",
    "6": "PENDING_CANCEL",
    "7": "STOPPED",
    "8": "REJECTED",
    "9": "SUSPENDED",
    "A": "PENDING_NEW",
    "B": "CALCULATED",
    "C": "EXPIRED",
    "D": "ACCEPTED_FOR_BIDDING",
    "E": "PENDING_REPLACE"
  },
  "40": {
    "1": "MARKET",
    "2": "LIMIT",
    "3": "STOP",
    "4": "STOP_LIMIT",
    "5": "MARKET_ON_CLOSE",
    "6": "WITH_OR_WITHOUT",
    "7": "LIMIT_OR_BETTER",
    "8": "LIMIT_WITH_OR_WITHOUT",
    "9": "ON_BASIS",
    "A": "ON_CLOSE",
    "B": "LIMIT_ON_CLOSE",
    "C": "FOREX_MARKET",
    "D": "PREVIOUSLY_QUOTED",
    "E": "PREVIOUSLY_INDICATED",
    "F": "FOREX_LIMIT",
    "G": "FOREX_SWAP",
    "H": "FOREX_PREVIOUSLY_QUOTED",
    "I": "FUNARI",
    "J": "MARKET_IF_TOUCHED",
    "K": "MARKET_WITH_LEFT_OVER_AS_LIMIT",
    "L": "PREVIOUS_FUND_VALUATION_POINT",
    "M": "NEXT_FUND_VALUATION_POINT",
    "P": "PEGGED",
    "Q": "COUNTER_ORDER_SELECTION"
  },
  "41": {
    "N": "NO",
    "Y": "YES"
  },
  "44": {
    "A": "AGENCY_SINGLE_ORDER",
    "B": "SHORT_EXEMPT_TRANSACTION_B",
    "C": "PROPRIETARY_NON_ALGORITHMIC_PROGRAM_TRADE",
    "D": "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG",
    "E": "SHORT_EXEMPT_TRANSACTION_FOR_PRINCIPAL",
    "F": "SHORT_EXEMPT_TRANSACTION_F",
    "H": "SHORT_EXEMPT_TRANSACTION_H",
    "I": "INDIVIDUAL_INVESTOR_SINGLE_ORDER",
    "J": "PROPRIETARY_ALGORITHMIC_PROGRAM_TRADING",
    "K": "AGENCY_ALGORITHMIC_PROGRAM_TRADING",
    "L": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFLIATED_WITH_THE_FIRM_CLEARING_THE_TRADE",
    "M": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER",
    "N": "AGENT_FOR_OTHER_MEMBER_NON_ALGORITHMIC_PROGRAM_TRADE",
    "O": "PROPRIETARY_TRANSACTIONS_FOR_COMPETING_MARKET_MAKER_THAT_IS_AFFILIATED_WITH_THE_CLEARING_MEMBER",
    "P": "PRINCIPAL",
    "R": "TRANSACTIONS_FOR_THE_ACCOUNT_OF_A_NON_MEMBER_COMPTING_MARKET_MAKER",
    "S": "SPECIALIST_TRADES",
    "T": "TRANSACTIONS_FOR_THE_ACCOUNT_OF_AN_UNAFFILIATED_MEMBERS_COMPETING_MARKET_MAKER",
    "U": "AGENCY_INDEX_ARBITRAGE",
    "W": "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER",
    "X": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE",
    "Y": "AGENCY_NON_ALGORITHMIC_PROGRAM_TRADE",
    "Z": "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER"
  },
  "48": {
    "1": "BUY",
    "2": "SELL",
    "3": "BUY_MINUS",
    "4": "SELL_PLUS",
    "5": "SELL_SHORT",
    "6": "SELL_SHORT_EXEMPT",
    "7": "UNDISCLOSED",
    "8": "CROSS",
    "9": "CROSS_SHORT",
    "A": "CROSS_SHORT_EXEMPT",
    "B": "AS_DEFINED",
    "C": "OPPOSITE",
    "D": "SUBSCRIBE",
    "E": "REDEEM",
    "F": "LEND",
    "G": "BORROW"
  },
  "55": {
    "0": "DAY",
    "1": "GOOD_TILL_CANCEL",
    "2": "AT_THE_OPENING",
    "3": "IMMEDIATE_OR_CANCEL",
    "4": "FILL_OR_KILL",
    "5": "GOOD_TILL_CROSSING",
    "6": "GOOD_TILL_DATE",
    "7": "AT_THE_CLOSE",
    "8": "GOOD_THROUGH_CROSSING",
    "9": "AT_CROSSING"
  },
  "60": {
    "0": "NORMAL",
    "1": "FLASH",
    "2": "BACKGROUND"
  },
  "62": {
    "0": "REGULAR",
    "1": "CASH",
    "2": "NEXT_DAY",
    "3": "T_PLUS_2",
    "4": "T_PLUS_3",
    "5": "T_PLUS_4",
    "6": "FUTURE",
    "7": "WHEN_AND_IF_ISSUED",
    "8": "SELLERS_OPTION",
    "9": "T_PLUS_5",
    "C": "FX_SPOT_NEXT_SETTLEMENT",
    "B": "BROKEN_DATE"
  },
  "64": {
    "CD": "EUCP_WITH_LUMP_SUM_INTEREST_RATHER_THAN_DISCOUNT_PRICE",
    "WI": "WHEN_ISSUED_FOR_A_SECURITY_TO_BE_REISSUED_UNDER_AN_OLD_CUSIP_OR_ISIN"
  },
  "66": {
    "0": "NEW",
    "1": "REPLACE",
    "2": "CANCEL",
    "3": "PRELIMINARY",
    "4": "CALCULATED",
    "5": "CALCULATED_WITHOUT_PRELIMINARY",
    "6": "REVERSAL"
  },
  "72": {
    "C": "CLOSE",
    "F": "FIFO",
    "O": "OPEN",
    "R": "ROLLED",
    "N": "CLOSE_BUT_NOTIFY_ON_OPEN",
    "D": "DEFAULT"
  },
  "78": {
    "0": "REGULAR",
    "1": "SOFT_DOLLAR",
    "2": "STEP_IN",
    "3": "STEP_OUT",
    "4": "SOFT_DOLLAR_STEP_IN",
    "5": "SOFT_DOLLAR_STEP_OUT",
    "6": "PLAN_SPONSOR"
  },
  "82": {
    "0": "ACCEPTED",
    "1": "BLOCK_LEVEL_REJECT",
    "2": "ACCOUNT_LEVEL_REJECT",
    "3": "RECEIVED",
    "4": "INCOMPLETE",
    "5": "REJECTED_BY_INTERMEDIARY",
    "6": "ALLOCATION_PENDING",
    "7": "REVERSED"
  },
  "88": {
    "0": "UNKNOWN_ACCOUNT",
    "1": "INCORRECT_QUANTITY",
    "2": "INCORRECT_AVERAGEG_PRICE",
    "3": "UNKNOWN_EXECUTING_BROKER_MNEMONIC",
    "4": "COMMISSION_DIFFERENCE",
    "5": "UNKNOWN_ORDERID",
    "6": "UNKNOWN_LISTID",
    "7": "OTHER_7",
    "8": "INCORRECT_ALLOCATED_QUANTITY",
    "9": "CALCULATION_DIFFERENCE",
    "10": "UNKNOWN_OR_STALE_EXECID",
    "11": "MISMATCHED_DATA",
    "12": "UNKNOWN_CLORDID",
    "13": "WAREHOUSE_REQUEST_REJECTED",
    "99": "OTHER_99"
  },
  "89": {
    "0": "NEW",
    "1": "REPLY",
    "2": "ADMIN_REPLY"
  },
  "95": {
    "N": "NO",
    "Y": "YES"
  },
  "98": {
    "0": "NONE",
    "1": "PKCS_1",
    "2": "DES",
    "3": "PKCS_3",
    "4": "PGP_4",
    "5": "PGP_5",
    "6": "PEM"
  },
  "99": {
    "0": "TOO_LATE_TO_CANCEL",
    "1": "UNKNOWN_ORDER",
    "2": "BROKER",
    "3": "ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS",
    "4": "UNABLE_TO_PROCESS_ORDER_MASS_CANCEL_REQUEST",
    "5": "ORIGORDMODTIME",
    "6": "DUPLICATE_CLORDID",
    "7": "PRICE_EXCEEDS_CURRENT_PRICE",
    "8": "PRICE_EXCEEDS_CURRENT_PRICE_BAND",
    "18": "INVALID_PRICE_INCREMENT",
    "99": "OTHER"
  },
  "103": {
    "0": "BROKER",
    "1": "UNKNOWN_SYMBOL",
    "2": "EXCHANGE_CLOSED",
    "3": "ORDER_EXCEEDS_LIMIT",
    "4": "TOO_LATE_TO_ENTER",
    "5": "UNKNOWN_ORDER",
    "6": "DUPLICATE_ORDER",
    "7": "DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER",
    "8": "STALE_ORDER",
    "9": "TRADE_ALONG_REQUIRED",
    "10": "INVALID_INVESTOR_ID",
    "11": "UNSUPPORTED_ORDER_CHARACTERISTIC",
    "12": "SURVEILLENCE_OPTION",
    "13": "INCORRECT_QUANTITY",
    "14": "INCORRECT_ALLOCATED_QUANTITY",
    "15": "UNKNOWN_ACCOUNT",
    "16": "PRICE_EXCEEDS_CURRENT_PRICE_BAND",
    "18": "INVALID_PRICE_INCREMENT",
    "99": "OTHER"
  },
  "104": {
    "A": "ALL_OR_NONE",
    "B": "MARKET_ON_CLOSE",
    "C": "AT_THE_CLOSE",
    "D": "VWAP",
    "I": "IN_TOUCH_WITH",
    "L": "LIMIT",
    "M": "MORE_BEHIND",
    "O": "AT_THE_OPEN",
    "P": "TAKING_A_POSITION",
    "Q": "AT_THE_MARKET",
    "R": "READY_TO_TRADE",
    "S": "PORTFOLIO_SHOWN",
    "T": "THROUGH_THE_DAY",
    "V": "VERSUS",
    "W": "INDICATION",
    "X": "CROSSING_OPPORTUNITY",
    "Y": "AT_THE_MIDPOINT",
    "Z": "PRE_OPEN"
  },
  "105": {
    "N": "NO",
    "Y": "YES"
  },
  "114": {
    "N": "NO",
    "Y": "YES"
  },
  "115": {
    "N": "NO",
    "Y": "YES"
  },
  "122": {
    "N": "NO",
    "Y": "YES"
  },
  "124": {
    "A": "UNKNOWN_SYMBOL",
    "B": "WRONG_SIDE",
    "C": "QUANTITY_EXCEEDS_ORDER",
    "D": "NO_MATCHING_ORDER",
    "E": "PRICE_EXCEEDS_LIMIT",
    "F": "CALCULATION_DIFFERENCE",
    "Z": "OTHER"
  },
  "128": {
    "N": "NO",
    "Y": "YES"
  },
  "131": {
    "1": "REGULATORY",
    "2": "TAX",
    "3": "LOCAL_COMMISSION",
    "4": "EXCHANGE_FEES",
    "5": "STAMP",
    "6": "LEVY",
    "7": "OTHER",
    "8": "MARKUP",
    "9": "CONSUMPTION_TAX",
    "10": "PER_TRANSACTION",
    "11": "CONVERSION",
    "12": "AGENT",
    "13": "TRANSFER_FEE",
    "14": "SECURITY_LENDING"
  },
  "140": {
    "N": "NO",
    "Y": "YES"
  },
  "142": {
    "0": "NEW",
    "3": "DONE_FOR_DAY",
    "4": "CANCELED",
    "5": "REPLACED",
    "6": "PENDING_CANCEL",
    "7": "STOPPED",
    "8": "REJECTED",
    "9": "SUSPENDED",
    "A": "PENDING_NEW",
    "B": "CALCULATED",
    "C": "EXPIRED",
    "D": "RESTATED",
    "E": "PENDING_REPLACE",
    "F": "TRADE",
    "G": "TRADE_CORRECT",
    "H": "TRADE_CANCEL",
    "I": "ORDER_STATUS",
    "J": "TRADE_IN_A_CLEARING_HOLD",
    "K": "TRADE_HAS_BEEN_RELEASED_TO_CLEARING",
    "L": "TRIGGERED_OR_ACTIVATED_BY_SYSTEM"
  },
  "151": {
    "M": "MULTIPLY",
    "D": "DIVIDE"
  },
  "157": {
    "0": "DEFAULT",
    "1": "STANDING_INSTRUCTIONS_PROVIDED",
    "2": "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING",
    "3": "SPECIFIC_ALLOCATION_ACCOUNT_STANDING",
    "4": "SPECIFIC_ORDER_FOR_A_SINGLE_ACCOUNT",
    "5": "REQUEST_REJECT"
  },
  "161": {
    "C": "CANCEL",
    "N": "NEW",
    "R": "REPLACE",
    "T": "RESTATE"
  },
  "164": {
    "1": "BROKERS_INSTRUCTIONS",
    "2": "INSTITUTIONS_INSTRUCTIONS",
    "3": "INVESTOR"
  },
  "166": {
    "CED": "CEDEL",
    "DTC": "DEPOSITORY_TRUST_COMPANY",
    "EUR": "EURO_CLEAR",
    "FED": "FEDERAL_BOOK_ENTRY",
    "ISO_Country_Code": "LOCAL_MARKET_SETTLE_LOCATION",
    "PNY": "PHYSICAL",
    "PTC": "PARTICIPANT_TRUST_COMPANY"
  },
  "167": {
    "ABS": "ASSET_BACKED_SECURITIES",
    "AMENDED": "AMENDED_RESTATED",
    "AN": "OTHER_ANTICIPATION_NOTES",
    "BA": "BANKERS_ACCEPTANCE",
    "BN": "BANK_NOTES",
    "BOX": "BILL_OF_EXCHANGES",
    "BRADY": "BRADY_BOND",
    "BRIDGE": "BRIDGE_LOAN",
    "BUYSELL": "BUY_SELLBACK",
    "CB": "CONVERTIBLE_BOND",
    "CD": "CERTIFICATE_OF_DEPOSIT",
    "CL": "CALL_LOANS",
    "CMBS": "CORP_MORTGAGE_BACKED_SECURITIES",
    "CMO": "COLLATERALIZED_MORTGAGE_OBLIGATION",
    "COFO": "CERTIFICATE_OF_OBLIGATION",
    "COFP": "CERTIFICATE_OF_PARTICIPATION",
    "CORP": "CORPORATE_BOND",
    "CP": "COMMERCIAL_PAPER",
    "CPP": "CORPORATE_PRIVATE_PLACEMENT",
    "CS": "COMMON_STOCK",
    "DEFLTED": "DEFAULTED",
    "DINP": "DEBTOR_IN_POSSESSION",
    "DN": "DEPOSIT_NOTES",
    "DUAL": "DUAL_CURRENCY",
    "EUCD": "EURO_CERTIFICATE_OF_DEPOSIT",
    "EUCORP": "EURO_CORPORATE_BOND",
    "EUCP": "EURO_COMMERCIAL_PAPER",
    "EUSOV": "EURO_SOVEREIGNS",
    "EUSUPRA": "EURO_SUPRANATIONAL_COUPONS",
    "FAC": "FEDERAL_AGENCY_COUPON",
    "FADN": "FEDERAL_AGENCY_DISCOUNT_NOTE",
    "FOR": "FOREIGN_EXCHANGE_CONTRACT",
    "FORWARD": "FORWARD",
    "FUT": "FUTURE",
    "GO": "GENERAL_OBLIGATION_BONDS",
    "IET": "IOETTE_MORTGAGE",
    "LOFC": "LETTER_OF_CREDIT",
    "LQN": "LIQUIDITY_NOTE",
    "MATURED": "MATURED",
    "MBS": "MORTGAGE_BACKED_SECURITIES",
    "MF": "MUTUAL_FUND",
    "MIO": "MORTGAGE_INTEREST_ONLY",
    "MLEG": "MULTILEG_INSTRUMENT",
    "MPO": "MORTGAGE_PRINCIPAL_ONLY",
    "MPP": "MORTGAGE_PRIVATE_PLACEMENT",
    "MPT": "MISCELLANEOUS_PASS_THROUGH",
    "MT": "MANDATORY_TENDER",
    "MTN": "MEDIUM_TERM_NOTES",
    "NONE": "NO_SECURITY_TYPE",
    "ONITE": "OVERNIGHT",
    "OPT": "OPTION",
    "PEF": "PRIVATE_EXPORT_FUNDING",
    "PFAND": "PFANDBRIEFE",
    "PN": "PROMISSORY_NOTE",
    "PS": "PREFERRED_STOCK",
    "PZFJ": "PLAZOS_FIJOS",
    "RAN": "REVENUE_ANTICIPATION_NOTE",
    "REPLACD": "REPLACED",
    "REPO": "REPURCHASE",
    "RETIRED": "RETIRED",
    "REV": "REVENUE_BONDS",
    "RVLV": "REVOLVER_LOAN",
    "RVLVTRM": "REVOLVER_TERM_LOAN",
    "SECLOAN": "SECURITIES_LOAN",
    "SECPLEDGE": "SECURITIES_PLEDGE",
    "SPCLA": "SPECIAL_ASSESSMENT",
    "SPCLO": "SPECIAL_OBLIGATION",
    "SPCLT": "SPECIAL_TAX",
    "STN": "SHORT_TERM_LOAN_NOTE",
    "STRUCT": "STRUCTURED_NOTES",
    "SUPRA": "USD_SUPRANATIONAL_COUPONS",
    "SWING": "SWING_LINE_FACILITY",
    "TAN": "TAX_ANTICIPATION_NOTE",
    "TAXA": "TAX_ALLOCATION",
    "TBA": "TO_BE_ANNOUNCED",
    "TBILL": "US_TREASURY_BILL_TBILL",
    "TBOND": "US_TREASURY_BOND",
    "TCAL": "PRINCIPAL_STRIP_OF_A_CALLABLE_BOND_OR_NOTE",
    "TD": "TIME_DEPOSIT",
    "TECP": "TAX_EXEMPT_COMMERCIAL_PAPER",
    "TERM": "TERM_LOAN",
    "TINT": "INTEREST_STRIP_FROM_ANY_BOND_OR_NOTE",
    "TIPS": "TREASURY_INFLATION_PROTECTED_SECURITIES",
    "TNOTE": "US_TREASURY_NOTE_TNOTE",
    "TPRN": "PRINCIPAL_STRIP_FROM_A_NON_CALLABLE_BOND_OR_NOTE",
    "TRAN": "TAX_REVENUE_ANTICIPATION_NOTE",
    "UST": "US_TREASURY_NOTE_UST",
    "USTB": "US_TREASURY_BILL_USTB",
    "VRDN": "VARIABLE_RATE_DEMAND_NOTE",
    "WAR": "WARRANT",
    "WITHDRN": "WITHDRAWN",
    "?": "WILDCARD_ENTRY_FOR_USE_ON_SECURITY_DEFINITION_REQUEST",
    "XCN": "EXTENDED_COMM_NOTE",
    "XLINKD": "INDEXED_LINKED",
    "YANK": "YANKEE_CORPORATE_BOND",
    "YCD": "YANKEE_CERTIFICATE_OF_DEPOSIT",
    "OOP": "OPTIONS_ON_PHYSICAL",
    "OOF": "OPTIONS_ON_FUTURES",
    "CASH": "CASH",
    "OOC": "OPTIONS_ON_COMBO",
    "IRS": "INTEREST_RATE_SWAP",
    "BDN": "BANK_DEPOSITORY_NOTE",
    "CAMM": "CANADIAN_MONEY_MARKETS",
    "CAN": "CANADIAN_TREASURY_NOTES",
    "CTB": "CANADIAN_TREASURY_BILLS",
    "CDS": "CREDIT_DEFAULT_SWAP",
    "CMB": "CANADIAN_MORTGAGE_BONDS",
    "EUFRN": "EURO_CORPORATE_FLOATING_RATE_NOTES",
    "FRN": "US_CORPORATE_FLOATING_RATE_NOTES",
    "PROV": "CANADIAN_PROVINCIAL_BONDS",
    "SLQN": "SECURED_LIQUIDITY_NOTE",
    "TB": "TREASURY_BILL",
    "TLQN": "TERM_LIQUIDITY_NOTE",
    "TMCP": "TAXABLE_MUNICIPAL_CP",
    "FXNDF": "NON_DELIVERABLE_FORWARD",
    "FXSPOT": "FX_SPOT",
    "FXFWD": "FX_FORWARD",
    "FXSWAP": "FX_SWAP"
  },
  "168": {
    "0": "OTHER",
    "1": "DTC_SID",
    "2": "THOMSON_ALERT",
    "3": "A_GLOBAL_CUSTODIAN",
    "4": "ACCOUNTNET"
  },
  "170": {
    "0": "VERSUS_PAYMENT_DELIVER",
    "1": "FREE_DELIVER",
    "2": "TRI_PARTY",
    "3": "HOLD_IN_CUSTODY"
  },
  "173": {
    "0": "FX_NETTING",
    "1": "FX_SWAP"
  },
  "198": {
    "0": "PUT",
    "1": "CALL"
  },
  "202": {
    "0": "COVERED",
    "1": "UNCOVERED"
  },
  "204": {
    "0": "CUSTOMER",
    "1": "FIRM"
  },
  "205": {
    "N": "NO",
    "Y": "YES"
  },
  "209": {
    "1": "MATCH",
    "2": "FORWARD",
    "3": "FORWARD_AND_MATCH"
  },
  "210": {
    "1": "TARGET_FIRM",
    "2": "TARGET_LIST",
    "3": "BLOCK_FIRM",
    "4": "BLOCK_LIST"
  },
  "217": {
    "1": "CURVE",
    "2": "5YR",
    "3": "OLD5",
    "4": "10YR",
    "5": "OLD10",
    "6": "30YR",
    "7": "OLD30",
    "8": "3MOLIBOR",
    "9": "6MOLIBOR"
  },
  "220": {
    "EONIA": "EONIA",
    "EUREPO": "EUREPO",
    "Euribor": "EURIBOR",
    "FutureSWAP": "FUTURESWAP",
    "LIBID": "LIBID",
    "LIBOR": "LIBOR",
    "MuniAAA": "MUNIAAA",
    "OTHER": "OTHER",
    "Pfandbriefe": "PFANDBRIEFE",
    "SONIA": "SONIA",
    "SWAP": "SWAP",
    "Treasury": "TREASURY"
  },
  "222": {
    "ABS": "ABSOLUTE_PREPAYMENT_SPEED",
    "AMT": "ALTERNATIVE_MINIMUM_TAX",
    "AUTOREINV": "AUTO_REINVESTMENT_AT_RATE_OR_BETTER",
    "BANKQUAL": "BANK_QUALIFIED",
    "BGNCON": "BARGAIN_CONDITIONS",
    "COUPON": "COUPON_RANGE",
    "CPP": "CONSTANT_PREPAYMENT_PENALTY",
    "CPR": "CONSTANT_PREPAYMENT_RATE",
    "CPY": "CONSTANT_PREPAYMENT_YIELD",
    "CURRENCY": "ISO_CURRENCY_CODE",
    "CUSTOMDATE": "CUSTOM_START_END_DATE",
    "GEOG": "GEOGRAPHICS_AND_RANGE",
    "HAIRCUT": "VALUATION_DISCOUNT",
    "HEP": "FINAL_CPR_OF_HOME_EQUITY_PREPAYMENT_CURVE",
    "INSURED": "INSURED",
    "ISSUE": "YEAR_OR_YEAR_MONTH_OF_ISSUE",
    "ISSUER": "ISSUERS_TICKER",
    "ISSUESIZE": "ISSUE_SIZE_RANGE",
    "LOOKBACK": "LOOKBACK_DAYS",
    "LOT": "EXPLICIT_LOT_IDENTIFIER",
    "LOTVAR": "LOT_VARIANCE",
    "MAT": "MATURITY_YEAR_AND_MONTH",
    "MATURITY": "MATURITY_RANGE",
    "MAXSUBS": "MAXIMUM_SUBSTITUTIONS",
    "MHP": "PERCENT_OF_MANUFACTURED_HOUSING_PREPAYMENT_CURVE",
    "MINDNOM": "MINIMUM_DENOMINATION",
    "MININCR": "MINIMUM_INCREMENT",
    "MINQTY": "MINIMUM_QUANTITY",
    "MPR": "MONTHLY_PREPAYMENT_RATE",
    "PAYFREQ": "PAYMENT_FREQUENCY_CALENDAR",
    "PIECES": "NUMBER_OF_PIECES",
    "PMAX": "POOLS_MAXIMUM",
    "PPC": "PERCENT_OF_PROSPECTUS_PREPAYMENT_CURVE",
    "PPL": "POOLS_PER_LOT",
    "PPM": "POOLS_PER_MILLION",
    "PPT": "POOLS_PER_TRADE",
    "PRICE": "PRICE_RANGE",
    "PRICEFREQ": "PRICING_FREQUENCY",
    "PROD": "PRODUCTION_YEAR",
    "PROTECT": "CALL_PROTECTION",
    "PSA": "PERCENT_OF_BMA_PREPAYMENT_CURVE",
    "PURPOSE": "PURPOSE",
    "PXSOURCE": "BENCHMARK_PRICE_SOURCE",
    "RATING": "RATING_SOURCE_AND_RANGE",
    "REDEMPTION": "TYPE_OF_REDEMPTION",
    "RESTRICTED": "RESTRICTED",
    "SECTOR": "MARKET_SECTOR",
    "SECTYPE": "SECURITY_TYPE_INCLUDED_OR_EXCLUDED",
    "SMM": "SINGLE_MONTHLY_MORTALITY",
    "STRUCT": "STRUCTURE",
    "SUBSFREQ": "SUBSTITUTIONS_FREQUENCY",
    "SUBSLEFT": "SUBSTITUTIONS_LEFT",
    "TEXT": "FREEFORM_TEXT",
    "TRDVAR": "TRADE_VARIANCE",
    "WAC": "WEIGHTED_AVERAGE_COUPON",
    "WAL": "WEIGHTED_AVERAGE_LIFE_COUPON",
    "WALA": "WEIGHTED_AVERAGE_LOAN_AGE",
    "WAM": "WEIGHTED_AVERAGE_MATURITY",
    "WHOLE": "WHOLE_POOL",
    "YIELD": "YIELD_RANGE",
    "AVFICO": "AVERAGE_FICO_SCORE",
    "AVSIZE": "AVERAGE_LOAN_SIZE",
    "MAXBAL": "MAXIMUM_LOAN_BALANCE",
    "POOL": "POOL_IDENTIFIER",
    "ROLLTYPE": "TYPE_OF_ROLL_TRADE",
    "REFTRADE": "REFERENCE_TO_ROLLING_OR_CLOSING_TRADE",
    "REFPRIN": "PRINCIPAL_OF_ROLLING_OR_CLOSING_TRADE",
    "REFINT": "INTEREST_OF_ROLLING_OR_CLOSING_TRADE",
    "AVAILQTY": "AVAILABLE_OFFER_QUANTITY_TO_BE_SHOWN_TO_THE_STREET",
    "BROKERCREDIT": "BROKERS_SALES_CREDIT",
    "INTERNALPX": "OFFER_PRICE_TO_BE_SHOWN_TO_INTERNAL_BROKERS",
    "INTERNALQTY": "OFFER_QUANTITY_TO_BE_SHOWN_TO_INTERNAL_BROKERS",
    "LEAVEQTY": "THE_MINIMUM_RESIDUAL_OFFER_QUANTITY",
    "MAXORDQTY": "MAXIMUM_ORDER_SIZE",
    "ORDRINCR": "ORDER_QUANTITY_INCREMENT",
    "PRIMARY": "PRIMARY_OR_SECONDARY_MARKET_INDICATOR",
    "SALESCREDITOVR": "BROKER_SALES_CREDIT_OVERRIDE",
    "TRADERCREDIT": "TRADERS_CREDIT",
    "DISCOUNT": "DISCOUNT_RATE",
    "YTM": "YIELD_TO_MATURITY"
  },
  "234": {
    "AFTERTAX": "AFTER_TAX_YIELD",
    "ANNUAL": "ANNUAL_YIELD",
    "ATISSUE": "YIELD_AT_ISSUE",
    "AVGMATURITY": "YIELD_TO_AVG_MATURITY",
    "BOOK": "BOOK_YIELD",
    "CALL": "YIELD_TO_NEXT_CALL",
    "CHANGE": "YIELD_CHANGE_SINCE_CLOSE",
    "CLOSE": "CLOSING_YIELD",
    "COMPOUND": "COMPOUND_YIELD",
    "CURRENT": "CURRENT_YIELD",
    "GOVTEQUIV": "GVNT_EQUIVALENT_YIELD",
    "GROSS": "TRUE_GROSS_YIELD",
    "INFLATION": "YIELD_WITH_INFLATION_ASSUMPTION",
    "INVERSEFLOATER": "INVERSE_FLOATER_BOND_YIELD",
    "LASTCLOSE": "MOST_RECENT_CLOSING_YIELD",
    "LASTMONTH": "CLOSING_YIELD_MOST_RECENT_MONTH",
    "LASTQUARTER": "CLOSING_YIELD_MOST_RECENT_QUARTER",
    "LASTYEAR": "CLOSING_YIELD_MOST_RECENT_YEAR",
    "LONGAVGLIFE": "YIELD_TO_LONGEST_AVERAGE_LIFE",
    "MARK": "MARK_TO_MARKET_YIELD",
    "MATURITY": "YIELD_TO_MATURITY",
    "NEXTREFUND": "YIELD_TO_NEXT_REFUND",
    "OPENAVG": "OPEN_AVERAGE_YIELD",
    "PREVCLOSE": "PREVIOUS_CLOSE_YIELD",
    "PROCEEDS": "PROCEEDS_YIELD",
    "PUT": "YIELD_TO_NEXT_PUT",
    "SEMIANNUAL": "SEMI_ANNUAL_YIELD",
    "SHORTAVGLIFE": "YIELD_TO_SHORTEST_AVERAGE_LIFE",
    "SIMPLE": "SIMPLE_YIELD",
    "TAXEQUIV": "TAX_EQUIVALENT_YIELD",
    "TENDER": "YIELD_TO_TENDER_DATE",
    "TRUE": "TRUE_YIELD",
    "VALUE1_32": "YIELD_VALUE_OF_1_32",
    "WORST": "YIELD_TO_WORST"
  },
  "236": {
    "N": "NO",
    "Y": "YES"
  },
  "259": {
    "0": "SNAPSHOT",
    "1": "SNAPSHOT_PLUS_UPDATES",
    "2": "DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST"
  },
  "264": {
    "0": "FULL_REFRESH",
    "1": "INCREMENTAL_REFRESH"
  },
  "266": {
    "Y": "YES",
    "N": "NO"
  },
  "267": {
    "0": "BID",
    "1": "OFFER",
    "2": "TRADE",
    "3": "INDEX_VALUE",
    "4": "OPENING_PRICE",
    "5": "CLOSING_PRICE",
    "6": "SETTLEMENT_PRICE",
    "7": "TRADING_SESSION_HIGH_PRICE",
    "8": "TRADING_SESSION_LOW_PRICE",
    "9": "TRADING_SESSION_VWAP_PRICE",
    "A": "IMBALANCE",
    "B": "TRADE_VOLUME",
    "C": "OPEN_INTEREST",
    "D": "COMPOSITE_UNDERLYING_PRICE",
    "E": "SIMULATED_SELL_PRICE",
    "F": "SIMULATED_BUY_PRICE",
    "G": "MARGIN_RATE",
    "H": "MID_PRICE",
    "J": "EMPTY_BOOK",
    "K": "SETTLE_HIGH_PRICE",
    "L": "SETTLE_LOW_PRICE",
    "M": "PRIOR_SETTLE_PRICE",
    "N": "SESSION_HIGH_BID",
    "O": "SESSION_LOW_OFFER",
    "P": "EARLY_PRICES",
    "Q": "AUCTION_CLEARING_PRICE",
    "S": "SWAP_VALUE_FACTOR",
    "R": "DAILY_VALUE_ADJUSTMENT_FOR_LONG_POSITIONS",
    "T": "CUMULATIVE_VALUE_ADJUSTMENT_FOR_LONG_POSITIONS",
    "U": "DAILY_VALUE_ADJUSTMENT_FOR_SHORT_POSITIONS",
    "V": "CUMULATIVE_VALUE_ADJUSTMENT_FOR_SHORT_POSITIONS",
    "Y": "RECOVERY_RATE",
    "Z": "RECOVERY_RATE_FOR_LONG",
    "a": "RECOVERY_RATE_FOR_SHORT",
    "W": "FIXING_PRICE",
    "X": "CASH_RATE"
  },
  "270": {
    "0": "PLUS_TICK",
    "1": "ZERO_PLUS_TICK",
    "2": "MINUS_TICK",
    "3": "ZERO_MINUS_TICK"
  },
  "275": {
    "0": "RESERVED_SAM",
    "1": "NO_ACTIVE_SAM",
    "2": "RESTRICTED",
    "3": "REST_OF_BOOK_VWAP",
    "4": "BETTER_PRICES_IN_CONDITIONAL_ORDERS",
    "5": "MEDIAN_PRICE",
    "6": "FULL_CURVE",
    "7": "FLAT_CURVE",
    "A": "OPEN_ACTIVE",
    "B": "CLOSED_INACTIVE",
    "C": "EXCHANGE_BEST",
    "D": "CONSOLIDATED_BEST",
    "E": "LOCKED",
    "F": "CROSSED",
    "G": "DEPTH",
    "H": "FAST_TRADING",
    "I": "NON_FIRM",
    "L": "MANUAL_SLOW_QUOTE",
    "J": "OUTRIGHT_PRICE",
    "K": "IMPLIED_PRICE",
    "M": "DEPTH_ON_OFFER",
    "N": "DEPTH_ON_BID",
    "O": "CLOSING",
    "P": "NEWS_DISSEMINATION",
    "Q": "TRADING_RANGE",
    "R": "ORDER_INFLUX",
    "S": "DUE_TO_RELATED",
    "T": "NEWS_PENDING",
    "U": "ADDITIONAL_INFO",
    "V": "ADDITIONAL_INFO_DUE_TO_RELATED",
    "W": "RESUME",
    "X": "VIEW_OF_COMMON",
    "Y": "VOLUME_ALERT",
    "Z": "ORDER_IMBALANCE",
    "a": "EQUIPMENT_CHANGEOVER",
    "b": "NO_OPEN",
    "c": "REGULAR_ETH",
    "d": "AUTOMATIC_EXECUTION",
    "e": "AUTOMATIC_EXECUTION_ETH",
    "f ": "FAST_MARKET_ETH",
    "g": "INACTIVE_ETH",
    "h": "ROTATION",
    "i": "ROTATION_ETH",
    "j": "HALT",
    "k": "HALT_ETH",
    "l": "DUE_TO_NEWS_DISSEMINATION",
    "m": "DUE_TO_NEWS_PENDING",
    "n": "TRADING_RESUME",
    "o": "OUT_OF_SEQUENCE",
    "p": "BID_SPECIALIST",
    "q": "OFFER_SPECIALIST",
    "r": "BID_OFFER_SPECIALIST",
    "s": "END_OF_DAY_SAM",
    "t": "FORBIDDEN_SAM",
    "u": "FROZEN_SAM",
    "v": "PREOPENING_SAM",
    "w": "OPENING_SAM",
    "x": "OPEN_SAM",
    "y": "SURVEILLANCE_SAM",
    "z": "SUSPENDED_SAM"
  },
  "277": {
    "0": "CANCEL",
    "1": "IMPLIED_TRADE",
    "2": "MARKETPLACE_ENTERED_TRADE",
    "3": "MULT_ASSET_CLASS_MULTILEG_TRADE",
    "4": "MULTILEG_TO_MULTILEG_TRADE",
    "A": "CASH",
    "B": "AVERAGE_PRICE_TRADE",
    "C": "CASH_TRADE",
    "D": "NEXT_DAY",
    "E": "OPENING_REOPENING_TRADE_DETAIL",
    "F": "INTRADAY_TRADE_DETAIL",
    "G": "RULE_127_TRADE",
    "H": "RULE_155_TRADE",
    "I": "SOLD_LAST",
    "J": "NEXT_DAY_TRADE",
    "K": "OPENED",
    "L": "SELLER",
    "M": "SOLD",
    "N": "STOPPED_STOCK",
    "P": "IMBALANCE_MORE_BUYERS",
    "Q": "IMBALANCE_MORE_SELLERS",
    "R": "OPENING_PRICE",
    "Y": "TRADES_RESULTING_FROM_MANUAL_SLOW_QUOTE",
    "Z": "TRADES_RESULTING_FROM_INTERMARKET_SWEEP",
    "S": "BARGAIN_CONDITION",
    "T": "CONVERTED_PRICE_INDICATOR",
    "U": "EXCHANGE_LAST",
    "V": "FINAL_PRICE_OF_SESSION",
    "W": "EX_PIT",
    "X": "CROSSED_X",
    "a": "VOLUME_ONLY",
    "b": "DIRECT_PLUS",
    "c": "ACQUISITION",
    "d": "BUNCHED",
    "e": "DISTRIBUTION",
    "f": "BUNCHED_SALE",
    "g": "SPLIT_TRADE",
    "h": "CANCEL_STOPPED",
    "i": "CANCEL_ETH",
    "j": "CANCEL_STOPPED_ETH",
    "k": "OUT_OF_SEQUENCE_ETH",
    "l": "CANCEL_LAST_ETH",
    "m": "SOLD_LAST_SALE_ETH",
    "n": "CANCEL_LAST",
    "o": "SOLD_LAST_SALE",
    "p": "CANCEL_OPEN",
    "q": "CANCEL_OPEN_ETH",
    "r": "OPENED_SALE_ETH",
    "s": "CANCEL_ONLY",
    "t": "CANCEL_ONLY_ETH",
    "u": "LATE_OPEN_ETH",
    "v": "AUTO_EXECUTION_ETH",
    "w": "REOPEN",
    "x": "REOPEN_ETH",
    "y": "ADJUSTED",
    "z": "ADJUSTED_ETH",
    "AA": "SPREAD",
    "AB": "SPREAD_ETH",
    "AC": "STRADDLE",
    "AD": "STRADDLE_ETH",
    "AE": "STOPPED",
    "AF": "STOPPED_ETH",
    "AG": "REGULAR_ETH",
    "AH": "COMBO",
    "AI": "COMBO_ETH",
    "AJ": "OFFICIAL_CLOSING_PRICE",
    "AK": "PRIOR_REFERENCE_PRICE",
    "AL": "STOPPED_SOLD_LAST",
    "AM": "STOPPED_OUT_OF_SEQUENCE",
    "AN": "OFFICAL_CLOSING_PRICE",
    "AO": "CROSSED_AO",
    "AP": "FAST_MARKET",
    "AQ": "AUTOMATIC_EXECUTION",
    "AR": "FORM_T",
    "AS": "BASKET_INDEX",
    "AT": "BURST_BASKET",
    "AV": "OUTSIDE_SPREAD"
  },
  "278": {
    "0": "NEW",
    "1": "CHANGE",
    "2": "DELETE",
    "3": "DELETE_THRU",
    "4": "DELETE_FROM",
    "5": "OVERLAY"
  },
  "280": {
    "0": "UNKNOWN_SYMBOL",
    "1": "DUPLICATE_MDREQID",
    "2": "INSUFFICIENT_BANDWIDTH",
    "3": "INSUFFICIENT_PERMISSIONS",
    "4": "UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE",
    "5": "UNSUPPORTED_MARKETDEPTH",
    "6": "UNSUPPORTED_MDUPDATETYPE",
    "7": "UNSUPPORTED_AGGREGATEDBOOK",
    "8": "UNSUPPORTED_MDENTRYTYPE",
    "9": "UNSUPPORTED_TRADINGSESSIONID",
    "A": "UNSUPPORTED_SCOPE",
    "B": "UNSUPPORTED_OPENCLOSESETTLEFLAG",
    "C": "UNSUPPORTED_MDIMPLICITDELETE",
    "D": "INSUFFICIENT_CREDIT"
  },
  "282": {
    "0": "CANCELLATION",
    "1": "ERROR"
  },
  "286": {
    "0": "DAILY_OPEN",
    "1": "SESSION_OPEN",
    "2": "DELIVERY_SETTLEMENT_ENTRY",
    "3": "EXPECTED_ENTRY",
    "4": "ENTRY_FROM_PREVIOUS_BUSINESS_DAY",
    "5": "THEORETICAL_PRICE_VALUE"
  },
  "287": {
    "1": "BANKRUPT",
    "2": "PENDING_DELISTING",
    "3": "RESTRICTED"
  },
  "292": {
    "A": "EX_DIVIDEND",
    "B": "EX_DISTRIBUTION",
    "C": "EX_RIGHTS",
    "D": "NEW",
    "E": "EX_INTEREST",
    "F": "CASH_DIVIDEND",
    "G": "STOCK_DIVIDEND",
    "H": "NON_INTEGER_STOCK_SPLIT",
    "I": "REVERSE_STOCK_SPLIT",
    "J": "STANDARD_INTEGER_STOCK_SPLIT",
    "K": "POSITION_CONSOLIDATION",
    "L": "LIQUIDATION_REORGANIZATION",
    "M": "MERGER_REORGANIZATION",
    "N": "RIGHTS_OFFERING",
    "O": "SHAREHOLDER_MEETING",
    "P": "SPINOFF",
    "Q": "TENDER_OFFER",
    "R": "WARRANT",
    "S": "SPECIAL_ACTION",
    "T": "SYMBOL_CONVERSION",
    "U": "CUSIP",
    "V": "LEAP_ROLLOVER",
    "W": "SUCCESSION_EVENT"
  },
  "293": {
    "0": "ACCEPTED",
    "1": "CANCEL_FOR_SYMBOL",
    "2": "CANCELED_FOR_SECURITY_TYPE",
    "3": "CANCELED_FOR_UNDERLYING",
    "4": "CANCELED_ALL",
    "5": "REJECTED",
    "6": "REMOVED_FROM_MARKET",
    "7": "EXPIRED",
    "8": "QUERY",
    "9": "QUOTE_NOT_FOUND",
    "10": "PENDING",
    "11": "PASS",
    "12": "LOCKED_MARKET_WARNING",
    "13": "CROSS_MARKET_WARNING",
    "14": "CANCELED_DUE_TO_LOCK_MARKET",
    "15": "CANCELED_DUE_TO_CROSS_MARKET",
    "16": "ACTIVE",
    "17": "CANCELED",
    "18": "UNSOLICITED_QUOTE_REPLENISHMENT",
    "19": "PENDING_END_TRADE",
    "20": "TOO_LATE_TO_END"
  },
  "298": {
    "1": "CANCEL_FOR_ONE_OR_MORE_SECURITIES",
    "2": "CANCEL_FOR_SECURITY_TYPE",
    "3": "CANCEL_FOR_UNDERLYING_SECURITY",
    "4": "CANCEL_ALL_QUOTES",
    "5": "CANCEL_QUOTE_SPECIFIED_IN_QUOTEID",
    "6": "CANCEL_BY_QUOTETYPE",
    "7": "CANCEL_FOR_SECURITY_ISSUER",
    "8": "CANCEL_FOR_ISSUER_OF_UNDERLYING_SECURITY"
  },
  "299": {
    "1": "UNKNOWN_SYMBOL",
    "2": "EXCHANGE",
    "3": "QUOTE_REQUEST_EXCEEDS_LIMIT",
    "4": "TOO_LATE_TO_ENTER",
    "5": "UNKNOWN_QUOTE",
    "6": "DUPLICATE_QUOTE",
    "7": "INVALID_BID_ASK_SPREAD",
    "8": "INVALID_PRICE",
    "9": "NOT_AUTHORIZED_TO_QUOTE_SECURITY",
    "10": "PRICE_EXCEEDS_CURRENT_PRICE_BAND",
    "11": "QUOTE_LOCKED",
    "12": "INVALID_OR_UNKNOWN_SECURITY_ISSUER",
    "13": "INVALID_OR_UNKNOWN_ISSUER_OF_UNDERLYING_SECURITY",
    "99": "OTHER"
  },
  "301": {
    "0": "NO_ACKNOWLEDGEMENT",
    "1": "ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES",
    "2": "ACKNOWLEDGE_EACH_QUOTE_MESSAGE",
    "3": "SUMMARY_ACKNOWLEDGEMENT"
  },
  "302": {
    "1": "MANUAL",
    "2": "AUTOMATIC"
  },
  "304": {
    "0": "REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS",
    "1": "REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED",
    "2": "REQUEST_LIST_SECURITY_TYPES",
    "3": "REQUEST_LIST_SECURITIES",
    "4": "SYMBOL",
    "5": "SECURITYTYPE_AND_OR_CFICODE",
    "6": "PRODUCT",
    "7": "TRADINGSESSIONID",
    "8": "ALL_SECURITIES",
    "9": "MARKETID_OR_MARKETID_PLUS_MARKETSEGMENTID"
  },
  "322": {
    "1": "ACCEPT_SECURITY_PROPOSAL_AS_IS",
    "2": "ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE",
    "3": "LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST",
    "4": "LIST_OF_SECURITIES_RETURNED_PER_REQUEST",
    "5": "REJECT_SECURITY_PROPOSAL",
    "6": "CANNOT_MATCH_SELECTION_CRITERIA"
  },
  "324": {
    "N": "NO",
    "Y": "YES"
  },
  "326": {
    "1": "OPENING_DELAY",
    "2": "TRADING_HALT",
    "3": "RESUME",
    "4": "NO_OPEN",
    "5": "PRICE_INDICATION",
    "6": "TRADING_RANGE_INDICATION",
    "7": "MARKET_IMBALANCE_BUY",
    "8": "MARKET_IMBALANCE_SELL",
    "9": "MARKET_ON_CLOSE_IMBALANCE_BUY",
    "10": "MARKET_ON_CLOSE_IMBALANCE_SELL",
    "11": "11",
    "12": "NO_MARKET_IMBALANCE",
    "13": "NO_MARKET_ON_CLOSE_IMBALANCE",
    "14": "ITS_PRE_OPENING",
    "15": "NEW_PRICE_INDICATION",
    "16": "TRADE_DISSEMINATION_TIME",
    "17": "READY_TO_TRADE",
    "18": "NOT_AVAILABLE_FOR_TRADING",
    "19": "NOT_TRADED_ON_THIS_MARKET",
    "20": "UNKNOWN_OR_INVALID",
    "21": "PRE_OPEN",
    "22": "OPENING_ROTATION",
    "23": "FAST_MARKET",
    "24": "PRE_CROSS",
    "25": "CROSS",
    "26": "POST_CLOSE"
  },
  "327": {
    "0": "NEWS_DISSEMINATION",
    "1": "ORDER_INFLUX",
    "2": "ORDER_IMBALANCE",
    "3": "ADDITIONAL_INFORMATION",
    "4": "NEWS_PENDING",
    "5": "EQUIPMENT_CHANGEOVER"
  },
  "328": {
    "N": "NO",
    "Y": "YES"
  },
  "329": {
    "N": "NO",
    "Y": "YES"
  },
  "330": {
    "1": "CANCEL",
    "2": "ERROR",
    "3": "CORRECTION"
  },
  "335": {
    "1": "DAY",
    "2": "HALFDAY",
    "3": "MORNING",
    "4": "AFTERNOON",
    "5": "EVENING",
    "6": "AFTER_HOURS"
  },
  "337": {
    "1": "ELECTRONIC",
    "2": "OPEN_OUTCRY",
    "3": "TWO_PARTY"
  },
  "339": {
    "1": "TESTING",
    "2": "SIMULATED",
    "3": "PRODUCTION"
  },
  "340": {
    "0": "UNKNOWN",
    "1": "HALTED",
    "2": "OPEN",
    "3": "CLOSED",
    "4": "PRE_OPEN",
    "5": "PRE_CLOSE",
    "6": "REQUEST_REJECTED"
  },
  "341": {
    "0": "INVALID_TAG_NUMBER",
    "1": "REQUIRED_TAG_MISSING",
    "2": "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE",
    "3": "UNDEFINED_TAG",
    "4": "TAG_SPECIFIED_WITHOUT_A_VALUE",
    "5": "VALUE_IS_INCORRECT",
    "6": "INCORRECT_DATA_FORMAT_FOR_VALUE",
    "7": "DECRYPTION_PROBLEM",
    "8": "SIGNATURE_PROBLEM",
    "9": "COMPID_PROBLEM",
    "10": "SENDINGTIME_ACCURACY_PROBLEM",
    "11": "INVALID_MSGTYPE",
    "12": "XML_VALIDATION_ERROR",
    "13": "TAG_APPEARS_MORE_THAN_ONCE",
    "14": "TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER",
    "15": "REPEATING_GROUP_FIELDS_OUT_OF_ORDER",
    "16": "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP",
    "17": "NON_DATA_VALUE_INCLUDES_FIELD_DELIMITER",
    "18": "INVALID_UNSUPPORTED_APPLICATION_VERSION",
    "99": "OTHER"
  },
  "374": {
    "C": "CANCEL",
    "N": "NO"
  },
  "375": {
    "N": "NO",
    "Y": "YES"
  },
  "378": {
    "0": "GT_CORPORATE_ACTION",
    "1": "GT_RENEWAL",
    "2": "VERBAL_CHANGE",
    "3": "REPRICING_OF_ORDER",
    "4": "BROKER_OPTION",
    "5": "PARTIAL_DECLINE_OF_ORDERQTY",
    "6": "CANCEL_ON_TRADING_HALT",
    "7": "CANCEL_ON_SYSTEM_FAILURE",
    "8": "MARKET",
    "9": "CANCELED_NOT_BEST",
    "10": "WAREHOUSE_RECAP",
    "11": "PEG_REFRESH",
    "99": "OTHER"
  },
  "379": {
    "0": "OTHER",
    "1": "UNKNOWN_ID",
    "2": "UNKNOWN_SECURITY",
    "3": "UNSUPPORTED_MESSAGE_TYPE",
    "4": "APPLICATION_NOT_AVAILABLE",
    "5": "CONDITIONALLY_REQUIRED_FIELD_MISSING",
    "6": "NOT_AUTHORIZED",
    "7": "DELIVERTO_FIRM_NOT_AVAILABLE_AT_THIS_TIME",
    "18": "INVALID_PRICE_INCREMENT"
  },
  "381": {
    "R": "RECEIVE",
    "S": "SEND"
  },
  "386": {
    "0": "RELATED_TO_DISPLAYED_PRICE",
    "1": "RELATED_TO_MARKET_PRICE",
    "2": "RELATED_TO_PRIMARY_PRICE",
    "3": "RELATED_TO_LOCAL_PRIMARY_PRICE",
    "4": "RELATED_TO_MIDPOINT_PRICE",
    "5": "RELATED_TO_LAST_TRADE_PRICE",
    "6": "RELATED_TO_VWAP",
    "7": "AVERAGE_PRICE_GUARANTEE"
  },
  "389": {
    "1": "NON_DISCLOSED_STYLE",
    "2": "DISCLOSED_SYTLE",
    "3": "NO_BIDDING_PROCESS"
  },
  "395": {
    "1": "SECTOR",
    "2": "COUNTRY",
    "3": "INDEX"
  },
  "400": {
    "1": "SIDE_VALUE_1",
    "2": "SIDE_VALUE_2"
  },
  "402": {
    "1": "5_DAY_MOVING_AVERAGE",
    "2": "20_DAY_MOVING_AVERAGE",
    "3": "NORMAL_MARKET_SIZE",
    "4": "OTHER"
  },
  "410": {
    "N": "NO",
    "Y": "YES"
  },
  "412": {
    "1": "BUY_SIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUE_REQUEST",
    "2": "SELL_SIDE_PERIODICALLY_SENDS_STATUS_USING_LIST_STATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD",
    "3": "REAL_TIME_EXECUTION_REPORTS"
  },
  "415": {
    "1": "NET",
    "2": "GROSS"
  },
  "417": {
    "A": "AGENCY",
    "G": "VWAP_GUARANTEE",
    "J": "GUARANTEED_CLOSE",
    "R": "RISK_TRADE"
  },
  "419": {
    "2": "CLOSING_PRICE_AT_MORNINGN_SESSION",
    "3": "CLOSING_PRICE",
    "4": "CURRENT_PRICE",
    "5": "SQ",
    "6": "VWAP_THROUGH_A_DAY",
    "7": "VWAP_THROUGH_A_MORNING_SESSION",
    "8": "VWAP_THROUGH_AN_AFTERNOON_SESSION",
    "9": "VWAP_THROUGH_A_DAY_EXCEPT_YORI",
    "A": "VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI",
    "B": "VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI",
    "C": "STRIKE",
    "D": "OPEN",
    "Z": "OTHERS"
  },
  "420": {
    "1": "PERCENTAGE",
    "2": "PER_UNIT",
    "3": "FIXED_AMOUNT",
    "4": "DISCOUNT",
    "5": "PREMIUM",
    "6": "SPREAD",
    "7": "TED_PRICE",
    "8": "TED_YIELD",
    "9": "YIELD",
    "10": "FIXED_CABINET_TRADE_PRICE",
    "11": "VARIABLE_CABINET_TRADE_PRICE",
    "13": "PRODUCT_TICKS_IN_HALFS",
    "14": "PRODUCT_TICKS_IN_FOURTHS",
    "15": "PRODUCT_TICKS_IN_EIGHTS",
    "16": "PRODUCT_TICKS_IN_SIXTEENTHS",
    "17": "PRODUCT_TICKS_IN_THIRTY_SECONDS",
    "18": "PRODUCT_TICKS_IN_SIXTY_FORTHS",
    "19": "PRODUCT_TICKS_IN_ONE_TWENTY_EIGHTS"
  },
  "424": {
    "0": "BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION",
    "1": "ACCUMULATE_EXECTUIONS_UNTIL_FORDER_IS_FILLED_OR_EXPIRES",
    "2": "ACCUMULATE_UNTIL_VERBALLLY_NOTIFIED_OTHERWISE"
  },
  "428": {
    "1": "ACK",
    "2": "RESPONSE",
    "3": "TIMED",
    "4": "EXEC_STARTED",
    "5": "ALL_DONE",
    "6": "ALERT"
  },
  "430": {
    "1": "NET",
    "2": "GROSS"
  },
  "431": {
    "1": "IN_BIDDING_PROCESS",
    "2": "RECEIVED_FOR_EXECUTION",
    "3": "EXECUTING",
    "4": "CANCELLING",
    "5": "ALERT",
    "6": "ALL_DONE",
    "7": "REJECT"
  },
  "432": {
    "1": "IMMEDIATE",
    "2": "WAIT_FOR_EXECUT_INSTRUCTION",
    "3": "EXCHANGE_SWITCH_CIV_ORDER_3",
    "4": "EXCHANGE_SWITCH_CIV_ORDER_4",
    "5": "EXCHANGE_SWITCH_CIV_ORDER_5"
  },
  "434": {
    "1": "ORDER_CANCEL_REQUEST",
    "2": "ORDER_CANCEL_REPLACE_REQUEST"
  },
  "435": {
    "1": "SINGLE_SECURITY",
    "2": "INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY",
    "3": "MULTI_LEG_SECURITY"
  },
  "443": {
    "1": "KOREAN_INVESTOR_ID",
    "2": "TAIWANESE_QUALIFIED_FOREIGN_INVESTOR_ID_QFII_FID",
    "3": "TAIWANESE_TRADING_ACCT",
    "4": "MALAYSIAN_CENTRAL_DEPOSITORY",
    "5": "CHINESE_INVESTOR_ID",
    "6": "UK_NATIONAL_INSURANCE_OR_PENSION_NUMBER",
    "7": "US_SOCIAL_SECURITY_NUMBER",
    "8": "US_EMPLOYER_OR_TAX_ID_NUMBER",
    "9": "AUSTRALIAN_BUSINESS_NUMBER",
    "A": "AUSTRALIAN_TAX_FILE_NUMBER",
    "B": "BIC",
    "C": "GENERALLY_ACCEPTED_MARKET_PARTICIPANT_IDENTIFIER",
    "D": "PROPRIETARY",
    "E": "ISO_COUNTRY_CODE",
    "F": "SETTLEMENT_ENTITY_LOCATION",
    "G": "MIC",
    "H": "CSD_PARTICIPANT_MEMBER_CODE",
    "I": "DIRECTED_BROKER_THREE_CHARACTER_ACRONYM_AS_DEFINED_IN_ISITC_ETC_BEST_PRACTICE_GUIDELINES_DOCUMENT"
  },
  "448": {
    "1": "EXECUTING_FIRM",
    "2": "BROKER_OF_CREDIT",
    "3": "CLIENT_ID",
    "4": "CLEARING_FIRM",
    "5": "INVESTOR_ID",
    "6": "INTRODUCING_FIRM",
    "7": "ENTERING_FIRM",
    "8": "LOCATE",
    "9": "FUND_MANAGER_CLIENT_ID",
    "10": "SETTLEMENT_LOCATION",
    "11": "ORDER_ORIGINATION_TRADER",
    "12": "EXECUTING_TRADER",
    "13": "ORDER_ORIGINATION_FIRM",
    "14": "GIVEUP_CLEARING_FIRM",
    "15": "CORRESPONDANT_CLEARING_FIRM",
    "16": "EXECUTING_SYSTEM",
    "17": "CONTRA_FIRM",
    "18": "CONTRA_CLEARING_FIRM",
    "19": "SPONSORING_FIRM",
    "20": "UNDERLYING_CONTRA_FIRM",
    "21": "CLEARING_ORGANIZATION",
    "22": "EXCHANGE",
    "24": "CUSTOMER_ACCOUNT",
    "25": "CORRESPONDENT_CLEARING_ORGANIZATION",
    "26": "CORRESPONDENT_BROKER",
    "27": "BUYER_SELLER",
    "28": "CUSTODIAN",
    "29": "INTERMEDIARY",
    "30": "AGENT",
    "31": "SUB_CUSTODIAN",
    "32": "BENEFICIARY",
    "33": "INTERESTED_PARTY",
    "34": "REGULATORY_BODY",
    "35": "LIQUIDITY_PROVIDER",
    "36": "ENTERING_TRADER",
    "37": "CONTRA_TRADER",
    "38": "POSITION_ACCOUNT",
    "39": "CONTRA_INVESTOR_ID",
    "40": "TRANSFER_TO_FIRM",
    "41": "CONTRA_POSITION_ACCOUNT",
    "42": "CONTRA_EXCHANGE",
    "43": "INTERNAL_CARRY_ACCOUNT",
    "44": "ORDER_ENTRY_OPERATOR_ID",
    "45": "SECONDARY_ACCOUNT_NUMBER",
    "46": "FOREIGN_FIRM",
    "47": "THIRD_PARTY_ALLOCATION_FIRM",
    "48": "CLAIMING_ACCOUNT",
    "49": "ASSET_MANAGER",
    "50": "PLEDGOR_ACCOUNT",
    "51": "PLEDGEE_ACCOUNT",
    "52": "LARGE_TRADER_REPORTABLE_ACCOUNT",
    "53": "TRADER_MNEMONIC",
    "54": "SENDER_LOCATION",
    "55": "SESSION_ID",
    "56": "ACCEPTABLE_COUNTERPARTY",
    "57": "UNACCEPTABLE_COUNTERPARTY",
    "58": "ENTERING_UNIT",
    "59": "EXECUTING_UNIT",
    "60": "INTRODUCING_BROKER",
    "61": "QUOTE_ORIGINATOR",
    "62": "REPORT_ORIGINATOR",
    "63": "SYSTEMATIC_INTERNALISER",
    "64": "MULTILATERAL_TRADING_FACILITY",
    "65": "REGULATED_MARKET",
    "66": "MARKET_MAKER",
    "67": "INVESTMENT_FIRM",
    "68": "HOST_COMPETENT_AUTHORITY",
    "69": "HOME_COMPETENT_AUTHORITY",
    "70": "COMPETENT_AUTHORITY_OF_THE_MOST_RELEVANT_MARKET_IN_TERMS_OF_LIQUIDITY",
    "71": "COMPETENT_AUTHORITY_OF_THE_TRANSACTION",
    "72": "REPORTING_INTERMEDIARY",
    "73": "EXECUTION_VENUE",
    "74": "MARKET_DATA_ENTRY_ORIGINATOR",
    "75": "LOCATION_ID",
    "76": "DESK_ID",
    "77": "MARKET_DATA_MARKET",
    "78": "ALLOCATION_ENTITY",
    "79": "PRIME_BROKER_PROVIDING_GENERAL_TRADE_SERVICES",
    "80": "STEP_OUT_FIRM",
    "81": "BROKERCLEARINGID",
    "82": "CENTRAL_REGISTRATION_DEPOSITORY",
    "83": "CLEARING_ACCOUNT",
    "84": "ACCEPTABLE_SETTLING_COUNTERPARTY",
    "85": "UNACCEPTABLE_SETTLING_COUNTERPARTY"
  },
  "453": {
    "1": "AGENCY",
    "2": "COMMODITY",
    "3": "CORPORATE",
    "4": "CURRENCY",
    "5": "EQUITY",
    "6": "GOVERNMENT",
    "7": "INDEX",
    "8": "LOAN",
    "9": "MONEYMARKET",
    "10": "MORTGAGE",
    "11": "MUNICIPAL",
    "12": "OTHER",
    "13": "FINANCING"
  },
  "461": {
    "N": "NO",
    "Y": "YES"
  },
  "465": {
    "1": "SHARES",
    "2": "BONDS",
    "3": "CURRENTFACE",
    "4": "ORIGINALFACE",
    "5": "CURRENCY",
    "6": "CONTRACTS",
    "7": "OTHER",
    "8": "PAR"
  },
  "466": {
    "0": "ROUND_TO_NEAREST",
    "1": "ROUND_DOWN",
    "2": "ROUND_UP"
  },
  "469": {
    "1": "CREST",
    "2": "NSCC",
    "3": "EUROCLEAR",
    "4": "CLEARSTREAM",
    "5": "CHEQUE",
    "6": "TELEGRAPHIC_TRANSFER",
    "7": "FED_WIRE",
    "8": "DIRECT_CREDIT",
    "9": "ACH_CREDIT",
    "10": "BPAY",
    "11": "HIGH_VALUE_CLEARING_SYSTEM_HVACS",
    "12": "REINVEST_IN_FUND"
  },
  "478": {
    "M": "NO_M",
    "N": "NO_N",
    "O": "NO_O",
    "Y": "YES"
  },
  "481": {
    "1": "EXEMPT_1",
    "2": "EXEMPT_2",
    "3": "EXEMPT_3",
    "N": "NOT_CHECKED",
    "Y": "PASSED"
  },
  "482": {
    "B": "BID_PRICE",
    "C": "CREATION_PRICE",
    "D": "CREATION_PRICE_PLUS_ADJUSTMENT_PERCENT",
    "E": "CREATION_PRICE_PLUS_ADJUSTMENT_AMOUNT",
    "O": "OFFER_PRICE",
    "P": "OFFER_PRICE_MINUS_ADJUSTMENT_PERCENT",
    "Q": "OFFER_PRICE_MINUS_ADJUSTMENT_AMOUNT",
    "S": "SINGLE_PRICE"
  },
  "485": {
    "0": "NEW",
    "1": "CANCEL",
    "2": "REPLACE",
    "3": "RELEASE",
    "4": "REVERSE",
    "5": "CANCEL_DUE_TO_BACK_OUT_OF_TRADE"
  },
  "488": {
    "1": "CREST",
    "2": "NSCC",
    "3": "EUROCLEAR",
    "4": "CLEARSTREAM",
    "5": "CHEQUE",
    "6": "TELEGRAPHIC_TRANSFER",
    "7": "FED_WIRE",
    "8": "DEBIT_CARD",
    "9": "DIRECT_DEBIT",
    "10": "DIRECT_CREDIT",
    "11": "CREDIT_CARD",
    "12": "ACH_DEBIT",
    "13": "ACH_CREDIT",
    "14": "BPAY",
    "15": "HIGH_VALUE_CLEARING_SYSTEM"
  },
  "493": {
    "0": "NONE_NOT_APPLICABLE",
    "1": "MAXI_ISA",
    "2": "TESSA",
    "3": "MINI_CASH_ISA",
    "4": "MINI_STOCKS_AND_SHARES_ISA",
    "5": "MINI_INSURANCE_ISA",
    "6": "CURRENT_YEAR_PAYMENT",
    "7": "PRIOR_YEAR_PAYMENT",
    "8": "ASSET_TRANSFER",
    "9": "EMPLOYEE_9",
    "10": "EMPLOYEE_10",
    "11": "EMPLOYER_11",
    "12": "EMPLOYER_12",
    "13": "NON_FUND_PROTOTYPE_IRA",
    "14": "NON_FUND_QUALIFIED_PLAN",
    "15": "DEFINED_CONTRIBUTION_PLAN",
    "16": "INDIVIDUAL_RETIREMENT_ACCOUNT_16",
    "17": "INDIVIDUAL_RETIREMENT_ACCOUNT_17",
    "18": "KEOGH",
    "19": "PROFIT_SHARING_PLAN",
    "20": "401",
    "21": "SELF_DIRECTED_IRA",
    "22": "403",
    "23": "457",
    "24": "ROTH_IRA_24",
    "25": "ROTH_IRA_25",
    "26": "ROTH_CONVERSION_IRA_26",
    "27": "ROTH_CONVERSION_IRA_27",
    "28": "EDUCATION_IRA_28",
    "29": "EDUCATION_IRA_29",
    "999": "OTHER"
  },
  "496": {
    "N": "NO",
    "Y": "YES"
  },
  "498": {
    "A": "ACCEPTED",
    "H": "HELD",
    "N": "REMINDER",
    "R": "REJECTED"
  },
  "507": {
    "1": "INVALID_UNACCEPTABLE_ACCOUNT_TYPE",
    "2": "INVALID_UNACCEPTABLE_TAX_EXEMPT_TYPE",
    "3": "INVALID_UNACCEPTABLE_OWNERSHIP_TYPE",
    "4": "INVALID_UNACCEPTABLE_NO_REG_DETAILS",
    "5": "INVALID_UNACCEPTABLE_REG_SEQ_NO",
    "6": "INVALID_UNACCEPTABLE_REG_DETAILS",
    "7": "INVALID_UNACCEPTABLE_MAILING_DETAILS",
    "8": "INVALID_UNACCEPTABLE_MAILING_INSTRUCTIONS",
    "9": "INVALID_UNACCEPTABLE_INVESTOR_ID",
    "10": "INVALID_UNACEEPTABLE_INVESTOR_ID_SOURCE",
    "11": "INVALID_UNACCEPTABLE_DATE_OF_BIRTH",
    "12": "INVALID_UNACCEPTABLE_INVESTOR_COUNTRY_OF_RESIDENCE",
    "13": "INVALID_UNACCEPTABLE_NO_DISTRIB_INSTNS",
    "14": "INVALID_UNACCEPTABLE_DISTRIB_PERCENTAGE",
    "15": "INVALID_UNACCEPTABLE_DISTRIB_PAYMENT_METHOD",
    "16": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NAME",
    "17": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_CODE",
    "18": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NUM",
    "99": "OTHER"
  },
  "508": {
    "0": "NEW",
    "1": "REPLACE",
    "2": "CANCEL"
  },
  "515": {
    "2": "JOINT_TRUSTEES",
    "J": "JOINT_INVESTORS",
    "T": "TENANTS_IN_COMMON"
  },
  "518": {
    "1": "COMMISSION_AMOUNT",
    "2": "COMMISSION_PERCENT",
    "3": "INITIAL_CHARGE_AMOUNT",
    "4": "INITIAL_CHARGE_PERCENT",
    "5": "DISCOUNT_AMOUNT",
    "6": "DISCOUNT_PERCENT",
    "7": "DILUTION_LEVY_AMOUNT",
    "8": "DILUTION_LEVY_PERCENT",
    "9": "EXIT_CHARGE_AMOUNT",
    "10": "EXIT_CHARGE_PERCENT",
    "11": "FUND_BASED_RENEWAL_COMMISSION_PERCENT",
    "12": "PROJECTED_FUND_VALUE",
    "13": "FUND_BASED_RENEWAL_COMMISSION_AMOUNT_13",
    "14": "FUND_BASED_RENEWAL_COMMISSION_AMOUNT_14",
    "15": "NET_SETTLEMENT_AMOUNT"
  },
  "520": {
    "1": "INDIVIDUAL_INVESTOR",
    "2": "PUBLIC_COMPANY",
    "3": "PRIVATE_COMPANY",
    "4": "INDIVIDUAL_TRUSTEE",
    "5": "COMPANY_TRUSTEE",
    "6": "PENSION_PLAN",
    "7": "CUSTODIAN_UNDER_GIFTS_TO_MINORS_ACT",
    "8": "TRUSTS",
    "9": "FIDUCIARIES",
    "10": "NETWORKING_SUB_ACCOUNT",
    "11": "NON_PROFIT_ORGANIZATION",
    "12": "CORPORATE_BODY",
    "13": "NOMINEE"
  },
  "523": {
    "A": "AGENCY",
    "G": "PROPRIETARY",
    "I": "INDIVIDUAL",
    "P": "PRINCIPAL",
    "R": "RISKLESS_PRINCIPAL",
    "W": "AGENT_FOR_OTHER_MEMBER"
  },
  "529": {
    "1": "PROGRAM_TRADE",
    "2": "INDEX_ARBITRAGE",
    "3": "NON_INDEX_ARBITRAGE",
    "4": "COMPETING_MARKET_MAKER",
    "5": "ACTING_AS_MARKET_MAKER_OR_SPECIALIST_IN_THE_SECURITY",
    "6": "ACTING_AS_MARKET_MAKER_OR_SPECIALIST_IN_THE_UNDERLYING_SECURITY_OF_A_DERIVATIVE_SECURITY",
    "7": "FOREIGN_ENTITY",
    "8": "EXTERNAL_MARKET_PARTICIPANT",
    "9": "EXTERNAL_INTER_CONNECTED_MARKET_LINKAGE",
    "A": "RISKLESS_ARBITRAGE",
    "B": "ISSUER_HOLDING",
    "C": "ISSUE_PRICE_STABILIZATION",
    "D": "NON_ALGORITHMIC",
    "E": "ALGORITHMIC",
    "F": "CROSS"
  },
  "530": {
    "1": "CANCEL_ORDERS_FOR_A_SECURITY",
    "2": "CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY",
    "3": "CANCEL_ORDERS_FOR_A_PRODUCT",
    "4": "CANCEL_ORDERS_FOR_A_CFICODE",
    "5": "CANCEL_ORDERS_FOR_A_SECURITYTYPE",
    "6": "CANCEL_ORDERS_FOR_A_TRADING_SESSION",
    "7": "CANCEL_ALL_ORDERS",
    "8": "CANCEL_ORDERS_FOR_A_MARKET",
    "9": "CANCEL_ORDERS_FOR_A_MARKET_SEGMENT",
    "A": "CANCEL_ORDERS_FOR_A_SECURITY_GROUP",
    "B": "CANCEL_FOR_SECURITY_ISSUER",
    "C": "CANCEL_FOR_ISSUER_OF_UNDERLYING_SECURITY"
  },
  "531": {
    "0": "CANCEL_REQUEST_REJECTED",
    "1": "CANCEL_ORDERS_FOR_A_SECURITY",
    "2": "CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY",
    "3": "CANCEL_ORDERS_FOR_A_PRODUCT",
    "4": "CANCEL_ORDERS_FOR_A_CFICODE",
    "5": "CANCEL_ORDERS_FOR_A_SECURITYTYPE",
    "6": "CANCEL_ORDERS_FOR_A_TRADING_SESSION",
    "7": "CANCEL_ALL_ORDERS",
    "8": "CANCEL_ORDERS_FOR_A_MARKET",
    "9": "CANCEL_ORDERS_FOR_A_MARKET_SEGMENT",
    "A": "CANCEL_ORDERS_FOR_A_SECURITY_GROUP",
    "B": "CANCEL_ORDERS_FOR_A_SECURITIES_ISSUER",
    "C": "CANCEL_ORDERS_FOR_ISSUER_OF_UNDERLYING_SECURITY"
  },
  "532": {
    "0": "MASS_CANCEL_NOT_SUPPORTED",
    "1": "INVALID_OR_UNKNOWN_SECURITY",
    "2": "INVALID_OR_UNKOWN_UNDERLYING_SECURITY",
    "3": "INVALID_OR_UNKNOWN_PRODUCT",
    "4": "INVALID_OR_UNKNOWN_CFICODE",
    "5": "INVALID_OR_UNKNOWN_SECURITYTYPE",
    "6": "INVALID_OR_UNKNOWN_TRADING_SESSION",
    "7": "INVALID_OR_UNKNOWN_MARKET",
    "8": "INVALID_OR_UNKOWN_MARKET_SEGMENT",
    "9": "INVALID_OR_UNKNOWN_SECURITY_GROUP",
    "10": "INVALID_OR_UNKNOWN_SECURITY_ISSUER",
    "11": "INVALID_OR_UNKNOWN_ISSUER_OF_UNDERLYING_SECURITY",
    "99": "OTHER"
  },
  "533": {
    "0": "INDICATIVE",
    "1": "TRADEABLE",
    "2": "RESTRICTED_TRADEABLE",
    "3": "COUNTER"
  },
  "538": {
    "1": "CASH",
    "2": "MARGIN_OPEN",
    "3": "MARGIN_CLOSE"
  },
  "545": {
    "1": "LOCAL_MARKET",
    "2": "NATIONAL",
    "3": "GLOBAL"
  },
  "547": {
    "N": "NO",
    "Y": "YES"
  },
  "548": {
    "1": "CROSS_AON",
    "2": "CROSS_IOC",
    "3": "CROSS_ONE_SIDE",
    "4": "CROSS_SAME_PRICE"
  },
  "550": {
    "0": "NONE",
    "1": "BUY_SIDE_IS_PRIORITIZED",
    "2": "SELL_SIDE_IS_PRIORITIZED"
  },
  "551": {
    "1": "ONE_SIDE",
    "2": "BOTH_SIDES"
  },
  "553": {
    "0": "SYMBOL",
    "1": "SECURITYTYPE_AND_OR_CFICODE",
    "2": "PRODUCT",
    "3": "TRADINGSESSIONID",
    "4": "ALL_SECURITIES",
    "5": "MARKETID_OR_MARKETID_PLUS_MARKETSEGMENTID"
  },
  "560": {
    "0": "VALID_REQUEST",
    "1": "INVALID_OR_UNSUPPORTED_REQUEST",
    "2": "NO_INSTRUMENTS_FOUND_THAT_MATCH_SELECTION_CRITERIA",
    "3": "NOT_AUTHORIZED_TO_RETRIEVE_INSTRUMENT_DATA",
    "4": "INSTRUMENT_DATA_TEMPORARILY_UNAVAILABLE",
    "5": "REQUEST_FOR_INSTRUMENT_DATA_NOT_SUPPORTED"
  },
  "561": {
    "0": "REPORT_BY_MULITLEG_SECURITY_ONLY",
    "1": "REPORT_BY_MULTILEG_SECURITY_AND_BY_INSTRUMENT_LEGS_BELONGING_TO_THE_MULTILEG_SECURITY",
    "2": "REPORT_BY_INSTRUMENT_LEGS_BELONGING_TO_THE_MULTILEG_SECURITY_ONLY"
  },
  "564": {
    "1": "UNKNOWN_OR_INVALID_TRADINGSESSIONID",
    "99": "OTHER"
  },
  "568": {
    "0": "ALL_TRADES",
    "1": "MATCHED_TRADES_MATCHING_CRITERIA_PROVIDED_ON_REQUEST",
    "2": "UNMATCHED_TRADES_THAT_MATCH_CRITERIA",
    "3": "UNREPORTED_TRADES_THAT_MATCH_CRITERIA",
    "4": "ADVISORIES_THAT_MATCH_CRITERIA"
  },
  "570": {
    "N": "NO",
    "Y": "YES"
  },
  "571": {
    "0": "COMPARED_MATCHED_OR_AFFIRMED",
    "1": "UNCOMPARED_UNMATCHED_OR_UNAFFIRMED",
    "2": "ADVISORY_OR_ALERT"
  },
  "574": {
    "1": "ONE_PARTY_TRADE_REPORT",
    "2": "TWO_PARTY_TRADE_REPORT",
    "3": "CONFIRMED_TRADE_REPORT",
    "4": "AUTO_MATCH",
    "5": "CROSS_AUCTION",
    "6": "COUNTER_ORDER_SELECTION",
    "7": "CALL_AUCTION",
    "8": "ISSUING_BUY_BACK_AUCTION",
    "A1": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME",
    "A2": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES",
    "A3": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME",
    "A4": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES",
    "A5": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADETYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME",
    "M3": "ACT_ACCEPTED_TRADE",
    "M4": "ACT_DEFAULT_TRADE",
    "M5": "ACT_DEFAULT_AFTER_M2",
    "M6": "ACT_M6_MATCH",
    "AQ": "COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST_ACCEPTS_PAIR_OFFS",
    "M1": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_MINUS_BADGES_AND_TIMES_ACT_M1_MATCH",
    "M2": "SUMMARIZED_MATCH_MINUS_BADGES_AND_TIMES_ACT_M2_MATCH",
    "MT": "OCS_LOCKED_IN_NON_ACT",
    "S1": "SUMMARIZED_MATCH_USING_A1_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIED",
    "S2": "SUMMARIZED_MATCH_USING_A2_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED",
    "S3": "SUMMARIZED_MATCH_USING_A3_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED",
    "S4": "SUMMARIZED_MATCH_USING_A4_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED",
    "S5": "SUMMARIZED_MATCH_USING_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED"
  },
  "575": {
    "N": "NO",
    "Y": "YES"
  },
  "576": {
    "0": "PROCESS_NORMALLY",
    "1": "EXCLUDE_FROM_ALL_NETTING",
    "2": "BILATERAL_NETTING_ONLY",
    "3": "EX_CLEARING",
    "4": "SPECIAL_TRADE",
    "5": "MULTILATERAL_NETTING",
    "6": "CLEAR_AGAINST_CENTRAL_COUNTERPARTY",
    "7": "EXCLUDE_FROM_CENTRAL_COUNTERPARTY",
    "8": "MANUAL_MODE",
    "9": "AUTOMATIC_POSTING_MODE",
    "10": "AUTOMATIC_GIVE_UP_MODE",
    "11": "QUALIFIED_SERVICE_REPRESENTATIVE_QSR",
    "12": "CUSTOMER_TRADE",
    "13": "SELF_CLEARING"
  },
  "578": {
    "1": "ACCOUNT_IS_CARRIED_ON_CUSTOMER_SIDE_OF_THE_BOOKS",
    "2": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS",
    "3": "HOUSE_TRADER",
    "4": "FLOOR_TRADER",
    "6": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS_AND_IS_CROSS_MARGINED",
    "7": "ACCOUNT_IS_HOUSE_TRADER_AND_IS_CROSS_MARGINED",
    "8": "JOINT_BACK_OFFICE_ACCOUNT"
  },
  "582": {
    "1": "MEMBER_TRADING_FOR_THEIR_OWN_ACCOUNT",
    "2": "CLEARING_FIRM_TRADING_FOR_ITS_PROPRIETARY_ACCOUNT",
    "3": "MEMBER_TRADING_FOR_ANOTHER_MEMBER",
    "4": "ALL_OTHER"
  },
  "583": {
    "1": "STATUS_FOR_ORDERS_FOR_A_SECURITY",
    "2": "STATUS_FOR_ORDERS_FOR_AN_UNDERLYING_SECURITY",
    "3": "STATUS_FOR_ORDERS_FOR_A_PRODUCT",
    "4": "STATUS_FOR_ORDERS_FOR_A_CFICODE",
    "5": "STATUS_FOR_ORDERS_FOR_A_SECURITYTYPE",
    "6": "STATUS_FOR_ORDERS_FOR_A_TRADING_SESSION",
    "7": "STATUS_FOR_ALL_ORDERS",
    "8": "STATUS_FOR_ORDERS_FOR_A_PARTYID",
    "9": "STATUS_FOR_SECURITY_ISSUER",
    "10": "STATUS_FOR_ISSUER_OF_UNDERLYING_SECURITY"
  },
  "586": {
    "0": "CAN_TRIGGER_BOOKING_WITHOUT_REFERENCE_TO_THE_ORDER_INITIATOR",
    "1": "SPEAK_WITH_ORDER_INITIATOR_BEFORE_BOOKING",
    "2": "ACCUMULATE"
  },
  "590": {
    "0": "EACH_PARTIAL_EXECUTION_IS_A_BOOKABLE_UNIT",
    "1": "AGGREGATE_PARTIAL_EXECUTIONS_ON_THIS_ORDER_AND_BOOK_ONE_TRADE_PER_ORDER",
    "2": "AGGREGATE_EXECUTIONS_FOR_THIS_SYMBOL_SIDE_AND_SETTLEMENT_DATE"
  },
  "591": {
    "0": "PRO_RATA",
    "1": "DO_NOT_PRO_RATA"
  },
  "592": {
    "1": "PRE_TRADING",
    "2": "OPENING_OR_OPENING_AUCTION",
    "3": "3",
    "4": "CLOSING_OR_CLOSING_AUCTION",
    "5": "POST_TRADING",
    "6": "INTRADAY_AUCTION",
    "7": "QUIESCENT"
  },
  "626": {
    "1": "CALCULATED",
    "2": "PRELIMINARY",
    "3": "SELLSIDE_CALCULATED_USING_PRELIMINARY",
    "4": "SELLSIDE_CALCULATED_WITHOUT_PRELIMINARY",
    "5": "READY_TO_BOOK",
    "6": "BUYSIDE_READY_TO_BOOK",
    "7": "WAREHOUSE_INSTRUCTION",
    "8": "REQUEST_TO_INTERMEDIARY",
    "9": "ACCEPT",
    "10": "REJECT",
    "11": "ACCEPT_PENDING",
    "12": "INCOMPLETE_GROUP",
    "13": "COMPLETE_GROUP",
    "14": "REVERSAL_PENDING"
  },
  "627": {
    "1": "1ST_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "2": "2ND_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "3": "3RD_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "4": "4TH_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "5": "5TH_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "9": "6TH_YEAR_DELEGATE_TRADING_FOR_OWN_ACCOUNT",
    "B": "CBOE_MEMBER",
    "C": "NON_MEMBER_AND_CUSTOMER",
    "E": "EQUITY_MEMBER_AND_CLEARING_MEMBER",
    "F": "FULL_AND_ASSOCIATE_MEMBER_TRADING_FOR_OWN_ACCOUNT_AND_AS_FLOOR_BROKERS",
    "H": "106H_AND_106J_FIRMS",
    "I": "GIM_IDEM_AND_COM_MEMBERSHIP_INTEREST_HOLDERS",
    "L": "LESSEE_106F_EMPLOYEES",
    "M": "ALL_OTHER_OWNERSHIP_TYPES"
  },
  "636": {
    "N": "NO",
    "Y": "YES"
  },
  "637": {
    "0": "PRIORITY_UNCHANGED",
    "1": "LOST_PRIORITY_AS_RESULT_OF_ORDER_CHANGE"
  },
  "639": {
    "N": "NO",
    "Y": "YES"
  },
  "651": {
    "0": "PENDING_APPROVAL",
    "1": "APPROVED",
    "2": "REJECTED",
    "3": "UNAUTHORIZED_REQUEST",
    "4": "INVALID_DEFINITION_REQUEST"
  },
  "654": {
    "1": "UNKNOWN_SYMBOL",
    "2": "EXCHANGE",
    "3": "QUOTE_REQUEST_EXCEEDS_LIMIT",
    "4": "TOO_LATE_TO_ENTER",
    "5": "INVALID_PRICE",
    "6": "NOT_AUTHORIZED_TO_REQUEST_QUOTE",
    "7": "NO_MATCH_FOR_INQUIRY",
    "8": "NO_MARKET_FOR_INSTRUMENT",
    "9": "NO_INVENTORY",
    "10": "PASS",
    "11": "INSUFFICIENT_CREDIT",
    "99": "OTHER"
  },
  "659": {
    "1": "BIC",
    "2": "SID_CODE",
    "3": "TFM",
    "4": "OMGEO",
    "5": "DTCC_CODE",
    "99": "OTHER"
  },
  "661": {
    "1": "RECEIVED",
    "2": "MISMATCHED_ACCOUNT",
    "3": "MISSING_SETTLEMENT_INSTRUCTIONS",
    "4": "CONFIRMED",
    "5": "REQUEST_REJECTED"
  },
  "666": {
    "0": "NEW",
    "1": "REPLACE",
    "2": "CANCEL"
  },
  "667": {
    "1": "BOOK_ENTRY",
    "2": "BEARER"
  },
  "669": {
    "1": "PAR_FOR_PAR",
    "2": "MODIFIED_DURATION",
    "4": "RISK",
    "5": "PROCEEDS"
  },
  "691": {
    "1": "PERCENT",
    "2": "PER_SHARE",
    "3": "FIXED_AMOUNT",
    "4": "DISCOUNT",
    "5": "PREMIUM",
    "6": "SPREAD",
    "7": "TED_PRICE",
    "8": "TED_YIELD",
    "9": "YIELD_SPREAD",
    "10": "YIELD"
  },
  "693": {
    "1": "HIT_LIFT",
    "2": "COUNTER",
    "3": "EXPIRED",
    "4": "COVER",
    "5": "DONE_AWAY",
    "6": "PASS",
    "7": "END_TRADE",
    "8": "TIMED_OUT"
  },
  "695": {
    "ALC": "ALLOCATION_TRADE_QTY",
    "AS": "OPTION_ASSIGNMENT",
    "ASF": "AS_OF_TRADE_QTY",
    "DLV": "DELIVERY_QTY",
    "ETR": "ELECTRONIC_TRADE_QTY",
    "EX": "OPTION_EXERCISE_QTY",
    "FIN": "END_OF_DAY_QTY",
    "IAS": "INTRA_SPREAD_QTY",
    "IES": "INTER_SPREAD_QTY",
    "PA": "ADJUSTMENT_QTY",
    "PIT": "PIT_TRADE_QTY",
    "SOD": "START_OF_DAY_QTY",
    "SPL": "INTEGRAL_SPLIT",
    "TA": "TRANSACTION_FROM_ASSIGNMENT",
    "TOT": "TOTAL_TRANSACTION_QTY",
    "TQ": "TRANSACTION_QUANTITY",
    "TRF": "TRANSFER_TRADE_QTY",
    "TX": "TRANSACTION_FROM_EXERCISE",
    "XM": "CROSS_MARGIN_QTY",
    "RCV": "RECEIVE_QUANTITY",
    "CAA": "CORPORATE_ACTION_ADJUSTMENT",
    "DN": "DELIVERY_NOTICE_QTY",
    "EP": "EXCHANGE_FOR_PHYSICAL_QTY",
    "PNTN": "PRIVATELY_NEGOTIATED_TRADE_QTY",
    "DLT": "NET_DELTA_QTY",
    "CEA": "CREDIT_EVENT_ADJUSTMENT",
    "SEA": "SUCCESSION_EVENT_ADJUSTMENT"
  },
  "704": {
    "0": "SUBMITTED",
    "1": "ACCEPTED",
    "2": "REJECTED"
  },
  "707": {
    "CASH": "CASH_AMOUNT",
    "CRES": "CASH_RESIDUAL_AMOUNT",
    "FMTM": "FINAL_MARK_TO_MARKET_AMOUNT",
    "IMTM": "INCREMENTAL_MARK_TO_MARKET_AMOUNT",
    "PREM": "PREMIUM_AMOUNT",
    "SMTM": "START_OF_DAY_MARK_TO_MARKET_AMOUNT",
    "TVAR": "TRADE_VARIATION_AMOUNT",
    "VADJ": "VALUE_ADJUSTED_AMOUNT",
    "SETL": "SETTLEMENT_VALUE",
    "ICPN": "INITIAL_TRADE_COUPON_AMOUNT",
    "ACPN": "ACCRUED_COUPON_AMOUNT",
    "CPN": "COUPON_AMOUNT",
    "IACPN": "INCREMENTAL_ACCRUED_COUPON",
    "CMTM": "COLLATERALIZED_MARK_TO_MARKET",
    "ICMTM": "INCREMENTAL_COLLATERALIZED_MARK_TO_MARKET",
    "DLV": "COMPENSATION_AMOUNT",
    "BANK": "TOTAL_BANKED_AMOUNT",
    "COLAT": "TOTAL_COLLATERALIZED_AMOUNT"
  },
  "708": {
    "1": "EXERCISE",
    "2": "DO_NOT_EXERCISE",
    "3": "POSITION_ADJUSTMENT",
    "4": "POSITION_CHANGE_SUBMISSION_MARGIN_DISPOSITION",
    "5": "PLEDGE",
    "6": "LARGE_TRADER_SUBMISSION"
  },
  "710": {
    "1": "NEW",
    "2": "REPLACE",
    "3": "CANCEL",
    "4": "REVERSE"
  },
  "713": {
    "ITD": "INTRADAY",
    "RTH": "REGULAR_TRADING_HOURS",
    "ETH": "ELECTRONIC_TRADING_HOURS",
    "EOD": "END_OF_DAY"
  },
  "717": {
    "0": "PROCESS_REQUEST_AS_MARGIN_DISPOSITION",
    "1": "DELTA_PLUS",
    "2": "DELTA_MINUS",
    "3": "FINAL"
  },
  "719": {
    "0": "ACCEPTED",
    "1": "ACCEPTED_WITH_WARNINGS",
    "2": "REJECTED",
    "3": "COMPLETED",
    "4": "COMPLETED_WITH_WARNINGS"
  },
  "723": {
    "0": "SUCCESSFUL_COMPLETION",
    "1": "REJECTED",
    "99": "OTHER"
  },
  "724": {
    "0": "POSITIONS",
    "1": "TRADES",
    "2": "EXERCISES",
    "3": "ASSIGNMENTS",
    "4": "SETTLEMENT_ACTIVITY",
    "5": "BACKOUT_MESSAGE",
    "6": "DELTA_POSITIONS"
  },
  "725": {
    "0": "INBAND",
    "1": "OUT_OF_BAND"
  },
  "726": {
    "0": "VALID_REQUEST",
    "1": "INVALID_OR_UNSUPPORTED_REQUEST",
    "2": "NO_POSITIONS_FOUND_THAT_MATCH_CRITERIA",
    "3": "NOT_AUTHORIZED_TO_REQUEST_POSITIONS",
    "4": "REQUEST_FOR_POSITION_NOT_SUPPORTED",
    "99": "OTHER"
  },
  "729": {
    "0": "COMPLETED",
    "1": "COMPLETED_WITH_WARNINGS",
    "2": "REJECTED"
  },
  "730": {
    "1": "FINAL",
    "2": "THEORETICAL"
  },
  "732": {
    "P": "PRO_RATA",
    "R": "RANDOM"
  },
  "745": {
    "A": "AUTOMATIC",
    "M": "MANUAL"
  },
  "748": {
    "0": "SUCCESSFUL",
    "1": "INVALID_OR_UNKNOWN_INSTRUMENT",
    "2": "INVALID_TYPE_OF_TRADE_REQUESTED",
    "3": "INVALID_PARTIES",
    "4": "INVALID_TRANSPORT_TYPE_REQUESTED",
    "5": "INVALID_DESTINATION_REQUESTED",
    "8": "TRADEREQUESTTYPE_NOT_SUPPORTED",
    "9": "NOT_AUTHORIZED",
    "99": "OTHER"
  },
  "750": {
    "0": "ACCEPTED",
    "1": "COMPLETED",
    "2": "REJECTED"
  },
  "751": {
    "0": "SUCCESSFUL",
    "1": "INVALID_PARTY_ONFORMATION",
    "2": "UNKNOWN_INSTRUMENT",
    "3": "UNAUTHORIZED_TO_REPORT_TRADES",
    "4": "INVALID_TRADE_TYPE",
    "99": "OTHER"
  },
  "752": {
    "1": "SINGLE_SECURITY",
    "2": "INDIVIDUAL_LEG_OF_A_MULTILEG_SECURITY",
    "3": "MULTILEG_SECURITY"
  },
  "753": {
    "1": "EXECUTION_TIME",
    "2": "TIME_IN",
    "3": "TIME_OUT",
    "4": "BROKER_RECEIPT",
    "5": "BROKER_EXECUTION",
    "6": "DESK_RECEIPT",
    "7": "SUBMISSION_TO_CLEARING"
  },
  "771": {
    "1": "STATUS",
    "2": "CONFIRMATION",
    "3": "CONFIRMATION_REQUEST_REJECTED"
  },
  "774": {
    "1": "MISMATCHED_ACCOUNT",
    "2": "MISSING_SETTLEMENT_INSTRUCTIONS",
    "99": "OTHER"
  },
  "775": {
    "0": "REGULAR_BOOKING",
    "1": "CFD",
    "2": "TOTAL_RETURN_SWAP"
  },
  "776": {
    "0": "USE_DEFAULT_INSTRUCTIONS",
    "1": "DERIVE_FROM_PARAMETERS_PROVIDED",
    "2": "FULL_DETAILS_PROVIDED",
    "3": "SSI_DB_IDS_PROVIDED",
    "4": "PHONE_FOR_INSTRUCTIONS"
  },
  "781": {
    "C": "CASH",
    "S": "SECURITIES"
  },
  "788": {
    "1": "OVERNIGHT",
    "2": "TERM",
    "3": "FLEXIBLE",
    "4": "OPEN"
  },
  "789": {
    "0": "UNABLE_TO_PROCESS_REQUEST",
    "1": "UNKNOWN_ACCOUNT",
    "2": "NO_MATCHING_SETTLEMENT_INSTRUCTIONS_FOUND",
    "99": "OTHER"
  },
  "793": {
    "2": "PRELIMINARY_REQUEST_TO_INTERMEDIARY",
    "3": "SELLSIDE_CALCULATED_USING_PRELIMINARY",
    "4": "SELLSIDE_CALCULATED_WITHOUT_PRELIMINARY",
    "5": "WAREHOUSE_RECAP",
    "8": "REQUEST_TO_INTERMEDIARY",
    "9": "ACCEPT",
    "10": "REJECT",
    "11": "ACCEPT_PENDING",
    "12": "COMPLETE",
    "14": "REVERSE_PENDING"
  },
  "795": {
    "1": "ORIGINAL_DETAILS_INCOMPLETE_INCORRECT",
    "2": "CHANGE_IN_UNDERLYING_ORDER_DETAILS",
    "99": "OTHER"
  },
  "797": {
    "1": "ACCOUNT_IS_CARRIED_PN_CUSTOMER_SIDE_OF_BOOKS",
    "2": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS",
    "3": "HOUSE_TRADER",
    "4": "FLOOR_TRADER",
    "6": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS_AND_IS_CROSS_MARGINED",
    "7": "ACCOUNT_IS_HOUSE_TRADER_AND_IS_CROSS_MARGINED",
    "8": "JOINT_BACK_OFFICE_ACCOUNT"
  },
  "799": {
    "1": "FIRM",
    "2": "PERSON",
    "3": "SYSTEM",
    "4": "APPLICATION",
    "5": "FULL_LEGAL_NAME_OF_FIRM",
    "6": "POSTAL_ADDRESS",
    "7": "PHONE_NUMBER",
    "8": "EMAIL_ADDRESS",
    "9": "CONTACT_NAME",
    "10": "SECURITIES_ACCOUNT_NUMBER",
    "11": "REGISTRATION_NUMBER",
    "12": "REGISTERED_ADDRESS_12",
    "13": "REGULATORY_STATUS",
    "14": "REGISTRATION_NAME",
    "15": "CASH_ACCOUNT_NUMBER",
    "16": "BIC",
    "17": "CSD_PARTICIPANT_MEMBER_CODE",
    "18": "REGISTERED_ADDRESS_18",
    "19": "FUND_ACCOUNT_NAME",
    "20": "TELEX_NUMBER",
    "21": "FAX_NUMBER",
    "22": "SECURITIES_ACCOUNT_NAME",
    "23": "CASH_ACCOUNT_NAME",
    "24": "DEPARTMENT",
    "25": "LOCATION_DESK",
    "26": "POSITION_ACCOUNT_TYPE",
    "27": "SECURITY_LOCATE_ID",
    "28": "MARKET_MAKER",
    "29": "ELIGIBLE_COUNTERPARTY",
    "30": "PROFESSIONAL_CLIENT",
    "31": "LOCATION",
    "32": "EXECUTION_VENUE",
    "33": "CURRENCY_DELIVERY_IDENTIFIER"
  },
  "804": {
    "1": "PENDING_ACCEPT",
    "2": "PENDING_RELEASE",
    "3": "PENDING_REVERSAL",
    "4": "ACCEPT",
    "5": "BLOCK_LEVEL_REJECT",
    "6": "ACCOUNT_LEVEL_REJECT"
  },
  "810": {
    "0": "NO_ACTION_TAKEN",
    "1": "QUEUE_FLUSHED",
    "2": "OVERLAY_LAST",
    "3": "END_SESSION"
  },
  "815": {
    "0": "NO_ACTION_TAKEN",
    "1": "QUEUE_FLUSHED",
    "2": "OVERLAY_LAST",
    "3": "END_SESSION"
  },
  "816": {
    "0": "NO_AVERAGE_PRICING",
    "1": "TRADE_IS_PART_OF_AN_AVERAGE_PRICE_GROUP_IDENTIFIED_BY_THE_TRADELINKID",
    "2": "LAST_TRADE_IS_THE_AVERAGE_PRICE_GROUP_IDENTIFIED_BY_THE_TRADELINKID"
  },
  "820": {
    "0": "ALLOCATION_NOT_REQUIRED",
    "1": "ALLOCATION_REQUIRED",
    "2": "USE_ALLOCATION_PROVIDED_WITH_THE_TRADE",
    "3": "ALLOCATION_GIVE_UP_EXECUTOR",
    "4": "ALLOCATION_FROM_EXECUTOR",
    "5": "ALLOCATION_TO_CLAIM_ACCOUNT"
  },
  "827": {
    "0": "EXPIRE_ON_TRADING_SESSION_CLOSE",
    "1": "EXPIRE_ON_TRADING_SESSION_OPEN",
    "2": "TRADING_ELIGIBILITY_EXPIRATION_SPECIFIED_IN_THE_DATE_AND_TIME_FIELDS_EVENTDATE"
  },
  "828": {
    "0": "REGULAR_TRADE",
    "1": "BLOCK_TRADE_1",
    "2": "EFP",
    "3": "TRANSFER",
    "4": "LATE_TRADE",
    "5": "T_TRADE",
    "6": "WEIGHTED_AVERAGE_PRICE_TRADE",
    "7": "BUNCHED_TRADE",
    "8": "LATE_BUNCHED_TRADE",
    "9": "PRIOR_REFERENCE_PRICE_TRADE",
    "10": "AFTER_HOURS_TRADE",
    "11": "EXCHANGE_FOR_RISK",
    "12": "EXCHANGE_FOR_SWAP",
    "13": "EXCHANGE_OF_FUTURES_FOR",
    "14": "EXCHANGE_OF_OPTIONS_FOR_OPTIONS",
    "15": "TRADING_AT_SETTLEMENT",
    "16": "ALL_OR_NONE",
    "17": "FUTURES_LARGE_ORDER_EXECUTION",
    "18": "EXCHANGE_OF_FUTURES_FOR_FUTURES",
    "19": "OPTION_INTERIM_TRADE",
    "20": "OPTION_CABINET_TRADE",
    "22": "PRIVATELY_NEGOTIATED_TRADES",
    "23": "SUBSTITUTION_OF_FUTURES_FOR_FORWARDS",
    "24": "ERROR_TRADE",
    "25": "SPECIAL_CUM_DIVIDEND",
    "26": "SPECIAL_EX_DIVIDEND",
    "27": "SPECIAL_CUM_COUPON",
    "28": "SPECIAL_EX_COUPON",
    "29": "CASH_SETTLEMENT",
    "30": "SPECIAL_PRICE",
    "31": "GUARANTEED_DELIVERY",
    "32": "SPECIAL_CUM_RIGHTS",
    "33": "SPECIAL_EX_RIGHTS",
    "34": "SPECIAL_CUM_CAPITAL_REPAYMENTS",
    "35": "SPECIAL_EX_CAPITAL_REPAYMENTS",
    "36": "SPECIAL_CUM_BONUS",
    "37": "SPECIAL_EX_BONUS",
    "38": "BLOCK_TRADE_38",
    "39": "WORKED_PRINCIPAL_TRADE",
    "40": "BLOCK_TRADES",
    "41": "NAME_CHANGE",
    "42": "PORTFOLIO_TRANSFER",
    "43": "PROROGATION_BUY",
    "44": "PROROGATION_SELL",
    "45": "OPTION_EXERCISE",
    "46": "DELTA_NEUTRAL_TRANSACTION",
    "47": "FINANCING_TRANSACTION",
    "48": "NON_STANDARD_SETTLEMENT",
    "49": "DERIVATIVE_RELATED_TRANSACTION",
    "50": "PORTFOLIO_TRADE",
    "51": "VOLUME_WEIGHTED_AVERAGE_TRADE",
    "52": "EXCHANGE_GRANTED_TRADE",
    "53": "REPURCHASE_AGREEMENT",
    "54": "OTC",
    "55": "EXCHANGE_BASIS_FACILITY"
  },
  "829": {
    "0": "CMTA",
    "1": "INTERNAL_TRANSFER_OR_ADJUSTMENT",
    "2": "EXTERNAL_TRANSFER_OR_TRANSFER_OF_ACCOUNT",
    "3": "REJECT_FOR_SUBMITTING_SIDE",
    "4": "ADVISORY_FOR_CONTRA_SIDE",
    "5": "OFFSET_DUE_TO_AN_ALLOCATION",
    "6": "ONSET_DUE_TO_AN_ALLOCATION",
    "7": "DIFFERENTIAL_SPREAD",
    "8": "IMPLIED_SPREAD_LEG_EXECUTED_AGAINST_AN_OUTRIGHT",
    "9": "TRANSACTION_FROM_EXERCISE",
    "10": "TRANSACTION_FROM_ASSIGNMENT",
    "11": "ACATS",
    "14": "AI",
    "15": "B",
    "16": "K",
    "17": "LC",
    "18": "M",
    "19": "N",
    "20": "NM",
    "21": "NR",
    "22": "P",
    "23": "PA",
    "24": "PC",
    "25": "PN",
    "26": "R",
    "27": "RO",
    "28": "RT",
    "29": "SW",
    "30": "T",
    "31": "WN",
    "32": "WT",
    "33": "OFF_HOURS_TRADE",
    "34": "ON_HOURS_TRADE",
    "35": "OTC_QUOTE",
    "36": "CONVERTED_SWAP",
    "37": "CROSSED_TRADE",
    "38": "INTERIM_PROTECTED_TRADE",
    "39": "LARGE_IN_SCALE"
  },
  "830": {
    "0": "FLOATING",
    "1": "FIXED"
  },
  "836": {
    "0": "PRICE",
    "1": "BASIS_POINTS",
    "2": "TICKS",
    "3": "PRICE_TIER"
  },
  "837": {
    "0": "OR_BETTER",
    "1": "STRICT",
    "2": "OR_WORSE"
  },
  "838": {
    "1": "MORE_AGGRESSIVE",
    "2": "MORE_PASSIVE"
  },
  "839": {
    "1": "LOCAL",
    "2": "NATIONAL",
    "3": "GLOBAL",
    "4": "NATIONAL_EXCLUDING_LOCAL"
  },
  "841": {
    "0": "FLOATING",
    "1": "FIXED"
  },
  "842": {
    "0": "PRICE",
    "1": "BASIS_POINTS",
    "2": "TICKS",
    "3": "PRICE_TIER"
  },
  "843": {
    "0": "OR_BETTER",
    "1": "STRICT",
    "2": "OR_WORSE"
  },
  "844": {
    "1": "MORE_AGGRESSIVE",
    "2": "MORE_PASSIVE"
  },
  "845": {
    "1": "LOCAL",
    "2": "NATIONAL",
    "3": "GLOBAL",
    "4": "NATIONAL_EXCLUDING_LOCAL"
  },
  "847": {
    "1": "VWAP",
    "2": "PARTICIPATE",
    "3": "MININIZE_MARKET_IMPACT"
  },
  "848": {
    "1": "ADDED_LIQUIDITY",
    "2": "REMOVED_LIQUIDITY",
    "3": "LIQUIDITY_ROUTED_OUT",
    "4": "AUCTION"
  },
  "852": {
    "N": "NO",
    "Y": "YES"
  },
  "853": {
    "0": "DEALER_SOLD_SHORT",
    "1": "DEALER_SOLD_SHORT_EXEMPT",
    "2": "SELLING_CUSTOMER_SOLD_SHORT",
    "3": "SELLING_CUSTOMER_SOLD_SHORT_EXEMPT",
    "4": "QUALIFIED_SERVICE_REPRESENTATIVE",
    "5": "QSR_OR_AGU_CONTRA_SIDE_SOLD_SHORT_EXEMPT"
  },
  "854": {
    "0": "UNITS",
    "1": "CONTRACTS",
    "2": "UNITS_OF_MEASURE_PER_TIME_UNIT"
  },
  "855": {
    "0": "SUBMIT",
    "1": "ALLEGED_1",
    "2": "ACCEPT",
    "3": "DECLINE",
    "4": "ADDENDUM",
    "5": "NO_WAS",
    "6": "TRADE_REPORT_CANCEL",
    "7": "7",
    "8": "DEFAULTED",
    "9": "INVALID_CMTA",
    "10": "PENDED",
    "11": "ALLEGED_NEW",
    "12": "ALLEGED_ADDENDUM",
    "13": "ALLEGED_NO_WAS",
    "14": "ALLEGED_TRADE_REPORT_CANCEL",
    "15": "ALLEGED_15"
  },
  "857": {
    "0": "NOT_SPECIFIED",
    "1": "EXPLICIT_LIST_PROVIDED"
  },
  "858": {
    "1": "PUT",
    "2": "CALL",
    "3": "TENDER",
    "4": "SINKING_FUND_CALL",
    "5": "ACTIVATION",
    "6": "INACTIVIATION",
    "7": "LAST_ELIGIBLE_TRADE_DATE",
    "8": "SWAP_START_DATE",
    "9": "SWAP_END_DATE",
    "10": "SWAP_ROLL_DATE",
    "11": "SWAP_NEXT_START_DATE",
    "12": "SWAP_NEXT_ROLL_DATE",
    "13": "FIRST_DELIVERY_DATE",
    "14": "LAST_DELIVERY_DATE",
    "15": "INITIAL_INVENTORY_DUE_DATE",
    "16": "FINAL_INVENTORY_DUE_DATE",
    "17": "FIRST_INTENT_DATE",
    "18": "LAST_INTENT_DATE",
    "19": "POSITION_REMOVAL_DATE",
    "99": "OTHER"
  },
  "866": {
    "1": "FLAT",
    "2": "ZERO_COUPON",
    "3": "INTEREST_BEARING",
    "4": "NO_PERIODIC_PAYMENTS",
    "5": "VARIABLE_RATE",
    "6": "LESS_FEE_FOR_PUT",
    "7": "STEPPED_COUPON",
    "8": "COUPON_PERIOD",
    "9": "WHEN_AND_IF_ISSUED",
    "10": "ORIGINAL_ISSUE_DISCOUNT",
    "11": "CALLABLE_PUTTABLE",
    "12": "ESCROWED_TO_MATURITY",
    "13": "ESCROWED_TO_REDEMPTION_DATE",
    "14": "PRE_REFUNDED",
    "15": "IN_DEFAULT",
    "16": "UNRATED",
    "17": "TAXABLE",
    "18": "INDEXED",
    "19": "SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX",
    "20": "ORIGINAL_ISSUE_DISCOUNT_PRICE_SUPPLY_PRICE_IN_THE_INSTRATTRIBVALUE",
    "21": "CALLABLE_BELOW_MATURITY_VALUE",
    "22": "CALLABLE_WITHOUT_NOTICE_BY_MAIL_TO_HOLDER_UNLESS_REGISTERED",
    "23": "PRICE_TICK_RULES_FOR_SECURITY",
    "24": "TRADE_TYPE_ELIGIBILITY_DETAILS_FOR_SECURITY",
    "25": "INSTRUMENT_DENOMINATOR",
    "26": "INSTRUMENT_NUMERATOR",
    "27": "INSTRUMENT_PRICE_PRECISION",
    "28": "INSTRUMENT_STRIKE_PRICE",
    "29": "TRADEABLE_INDICATOR",
    "99": "TEXT_SUPPLY_THE_TEXT_OF_THE_ATTRIBUTE_OR_DISCLAIMER_IN_THE_INSTRATTRIBVALUE"
  },
  "872": {
    "1": "3",
    "2": "4",
    "99": "OTHER"
  },
  "876": {
    "0": "ABSOLUTE",
    "1": "PER_UNIT",
    "2": "PERCENTAGE"
  },
  "892": {
    "N": "NO",
    "Y": "YES"
  },
  "894": {
    "0": "INITIAL",
    "1": "SCHEDULED",
    "2": "TIME_WARNING",
    "3": "MARGIN_DEFICIENCY",
    "4": "MARGIN_EXCESS",
    "5": "FORWARD_COLLATERAL_DEMAND",
    "6": "EVENT_OF_DEFAULT",
    "7": "ADVERSE_TAX_EVENT"
  },
  "896": {
    "0": "TRADE_DATE",
    "1": "GC_INSTRUMENT",
    "2": "COLLATERAL_INSTRUMENT",
    "3": "SUBSTITUTION_ELIGIBLE",
    "4": "NOT_ASSIGNED",
    "5": "PARTIALLY_ASSIGNED",
    "6": "FULLY_ASSIGNED",
    "7": "OUTSTANDING_TRADES"
  },
  "897": {
    "0": "NEW",
    "1": "REPLACE",
    "2": "CANCEL",
    "3": "RELEASE",
    "4": "REVERSE"
  },
  "904": {
    "0": "RECEIVED",
    "1": "ACCEPTED",
    "2": "DECLINED",
    "3": "REJECTED"
  },
  "906": {
    "0": "UNKNOWN_DEAL",
    "1": "UNKNOWN_OR_INVALID_INSTRUMENT",
    "2": "UNAUTHORIZED_TRANSACTION",
    "3": "INSUFFICIENT_COLLATERAL",
    "4": "INVALID_TYPE_OF_COLLATERAL",
    "5": "EXCESSIVE_SUBSTITUTION",
    "99": "OTHER"
  },
  "907": {
    "0": "UNASSIGNED",
    "1": "PARTIALLY_ASSIGNED",
    "2": "ASSIGNMENT_PROPOSED",
    "3": "ASSIGNED",
    "4": "CHALLENGED"
  },
  "911": {
    "N": "NO",
    "Y": "YES"
  },
  "913": {
    "0": "VERSUS_PAYMENT_DELIVER",
    "1": "FREE_DELIVER",
    "2": "TRI_PARTY",
    "3": "HOLD_IN_CUSTODY"
  },
  "920": {
    "1": "LOG_ON_USER",
    "2": "LOG_OFF_USER",
    "3": "CHANGE_PASSWORD_FOR_USER",
    "4": "REQUEST_INDIVIDUAL_USER_STATUS"
  },
  "925": {
    "1": "LOGGED_IN",
    "2": "NOT_LOGGED_IN",
    "3": "USER_NOT_RECOGNISED",
    "4": "PASSWORD_INCORRECT",
    "5": "PASSWORD_CHANGED",
    "6": "OTHER",
    "7": "FORCED_USER_LOGOUT_BY_EXCHANGE",
    "8": "SESSION_SHUTDOWN_WARNING"
  },
  "927": {
    "1": "CONNECTED",
    "2": "NOT_CONNECTED_2",
    "3": "NOT_CONNECTED_3",
    "4": "IN_PROCESS"
  },
  "929": {
    "1": "SNAPSHOT",
    "2": "SUBSCRIBE",
    "4": "STOP_SUBSCRIBING",
    "8": "LEVEL_OF_DETAIL_THEN_NOCOMPIDS_BECOMES_REQUIRED"
  },
  "936": {
    "1": "FULL",
    "2": "INCREMENTAL_UPDATE"
  },
  "938": {
    "0": "ACCEPTED",
    "1": "REJECTED",
    "3": "ACCEPTED_WITH_ERRORS"
  },
  "940": {
    "1": "RECEIVED",
    "2": "CONFIRM_REJECTED_IE_NOT_AFFIRMED",
    "3": "AFFIRMED"
  },
  "941": {
    "0": "RETAIN",
    "1": "ADD",
    "2": "REMOVE"
  },
  "945": {
    "0": "ACCEPTED",
    "1": "ACCEPTED_WITH_WARNINGS",
    "2": "COMPLETED",
    "3": "COMPLETED_WITH_WARNINGS",
    "4": "REJECTED"
  },
  "946": {
    "0": "SUCCESSFUL",
    "1": "INVALID_OR_UNKNOWN_INSTRUMENT",
    "2": "INVALID_OR_UNKNOWN_COLLATERAL_TYPE",
    "3": "INVALID_PARTIES",
    "4": "INVALID_TRANSPORT_TYPE_REQUESTED",
    "5": "INVALID_DESTINATION_REQUESTED",
    "6": "NO_COLLATERAL_FOUND_FOR_THE_TRADE_SPECIFIED",
    "7": "NO_COLLATERAL_FOUND_FOR_THE_ORDER_SPECIFIED",
    "8": "COLLATERAL_INQUIRY_TYPE_NOT_SUPPORTED",
    "9": "UNAUTHORIZED_FOR_COLLATERAL_INQUIRY",
    "99": "OTHER"
  },
  "947": {
    "1": "INT",
    "2": "LENGTH",
    "3": "NUMINGROUP",
    "4": "SEQNUM",
    "5": "TAGNUM",
    "6": "FLOAT",
    "7": "QTY",
    "8": "PRICE",
    "9": "PRICEOFFSET",
    "10": "AMT",
    "11": "PERCENTAGE",
    "12": "CHAR",
    "13": "BOOLEAN",
    "14": "STRING",
    "15": "MULTIPLECHARVALUE",
    "16": "CURRENCY",
    "17": "EXCHANGE",
    "18": "MONTHYEAR",
    "19": "UTCTIMESTAMP",
    "20": "UTCTIMEONLY",
    "21": "LOCALMKTDATE",
    "22": "UTCDATEONLY",
    "23": "DATA",
    "24": "MULTIPLESTRINGVALUE",
    "25": "COUNTRY",
    "26": "LANGUAGE",
    "27": "TZTIMEONLY",
    "28": "TZTIMESTAMP",
    "29": "TENOR"
  },
  "960": {
    "1": "ACTIVE",
    "2": "INACTIVE"
  },
  "966": {
    "FIXED": "FIXED",
    "DIFF": "DIFF"
  },
  "975": {
    "2": "T_PLUS_1",
    "4": "T_PLUS_3",
    "5": "T_PLUS_4"
  },
  "976": {
    "A": "ADD",
    "D": "DELETE",
    "M": "MODIFY"
  },
  "981": {
    "1": "AUTO_EXERCISE",
    "2": "NON_AUTO_EXERCISE",
    "3": "FINAL_WILL_BE_EXERCISED",
    "4": "CONTRARY_INTENTION",
    "5": "DIFFERENCE"
  },
  "983": {
    "1": "SUB_ALLOCATE",
    "2": "THIRD_PARTY_ALLOCATION"
  },
  "993": {
    "MWh": "MEGAWATT_HOURS",
    "MMBtu": "ONE_MILLION_BTU",
    "Bbl": "BARRELS",
    "Gal": "GALLONS",
    "t": "METRIC_TONS",
    "tn": "TONS",
    "MMbbl": "MILLION_BARRELS",
    "lbs": "POUNDS",
    "oz_tr": "TROY_OUNCES",
    "USD": "US_DOLLARS",
    "Bcf": "BILLION_CUBIC_FEET",
    "Bu": "BUSHELS",
    "Alw": "ALLOWANCES"
  },
  "997": {
    "S": "SECOND",
    "Min": "MINUTE",
    "H": "HOUR",
    "D": "DAY",
    "Wk": "WEEK",
    "Mo": "MONTH",
    "Yr": "YEAR"
  },
  "998": {
    "1": "AUTOMATIC",
    "2": "GUARANTOR",
    "3": "MANUAL"
  },
  "1003": {
    "0": "FALSE",
    "1": "TRUE"
  },
  "1016": {
    "1": "TOP_OF_BOOK",
    "2": "PRICE_DEPTH",
    "3": "ORDER_DEPTH"
  },
  "1022": {
    "0": "BOOK",
    "1": "OFF_BOOK",
    "2": "CROSS"
  },
  "1025": {
    "ADD": "ADD_ON_ORDER",
    "AON": "ALL_OR_NONE",
    "CNH": "CASH_NOT_HELD",
    "DIR": "DIRECTED_ORDER",
    "E.W": "EXCHANGE_FOR_PHYSICAL_TRANSACTION",
    "FOK": "FILL_OR_KILL",
    "IO": "IMBALANCE_ONLY",
    "IOC": "IMMEDIATE_OR_CANCEL",
    "LOO": "LIMIT_ON_OPEN",
    "LOC": "LIMIT_ON_CLOSE",
    "MAO": "MARKET_AT_OPEN",
    "MAC": "MARKET_AT_CLOSE",
    "MOO": "MARKET_ON_OPEN",
    "MOC": "MARKET_ON_CLOSE",
    "MQT": "MINIMUM_QUANTITY",
    "NH": "NOT_HELD",
    "OVD": "OVER_THE_DAY",
    "PEG": "PEGGED",
    "RSV": "RESERVE_SIZE_ORDER",
    "S.W": "STOP_STOCK_TRANSACTION",
    "SCL": "SCALE",
    "TMO": "TIME_ORDER",
    "TS": "TRAILING_STOP",
    "WRK": "WORK"
  },
  "1032": {
    "1": "NASD_OATS"
  },
  "1033": {
    "A": "AGENCY",
    "AR": "ARBITRAGE",
    "D": "DERIVATIVES",
    "IN": "INTERNATIONAL",
    "IS": "INSTITUTIONAL",
    "O": "OTHER",
    "PF": "PREFERRED_TRADING",
    "PR": "PROPRIETARY",
    "PT": "PROGRAM_TRADING",
    "S": "SALES",
    "T": "TRADING"
  },
  "1034": {
    "1": "NASD_OATS"
  },
  "1035": {
    "ADD": "ADD_ON_ORDER",
    "AON": "ALL_OR_NONE",
    "CNH": "CASH_NOT_HELD",
    "DIR": "DIRECTED_ORDER",
    "E.W": "EXCHANGE_FOR_PHYSICAL_TRANSACTION",
    "FOK": "FILL_OR_KILL",
    "IO": "IMBALANCE_ONLY",
    "IOC": "IMMEDIATE_OR_CANCEL",
    "LOO": "LIMIT_ON_OPEN",
    "LOC": "LIMIT_ON_CLOSE",
    "MAO": "MARKET_AT_OPEN",
    "MAC": "MARKET_AT_CLOSE",
    "MOO": "MARKET_ON_OPEN",
    "MOC": "MARKET_ON_CLOSE",
    "MQT": "MINIMUM_QUANTITY",
    "NH": "NOT_HELD",
    "OVD": "OVER_THE_DAY",
    "PEG": "PEGGED",
    "RSV": "RESERVE_SIZE_ORDER",
    "S.W": "STOP_STOCK_TRANSACTION",
    "SCL": "SCALE",
    "TMO": "TIME_ORDER",
    "TS": "TRAILING_STOP",
    "WRK": "WORK"
  },
  "1036": {
    "0": "RECEIVED_NOT_YET_PROCESSED",
    "1": "ACCEPTED",
    "2": "DONT_KNOW"
  },
  "1037": {
    "0": "SPECIFIC_DEPOSIT",
    "1": "GENERAL"
  },
  "1044": {
    "M": "MULTIPLY",
    "D": "DIVIDE"
  },
  "1047": {
    "O": "OPEN",
    "C": "CLOSE",
    "R": "ROLLED",
    "F": "FIFO"
  },
  "1048": {
    "A": "AGENT",
    "P": "PRINCIPAL",
    "R": "RISKLESS_PRINCIPAL"
  },
  "1049": {
    "Y": "YES",
    "N": "NO"
  },
  "1058": {
    "0": "INDICATIVE",
    "1": "TRADEABLE",
    "2": "RESTRICTED_TRADEABLE",
    "3": "COUNTER",
    "4": "INDICATIVE_AND_TRADEABLE"
  },
  "1071": {
    "0": "SECONDARYORDERID",
    "1": "ORDERID",
    "2": "MDENTRYID",
    "3": "QUOTEENTRYID",
    "4": "ORIGINAL_ORDER_ID"
  },
  "1082": {
    "1": "IMMEDIATE",
    "2": "EXHAUST"
  },
  "1084": {
    "1": "INITIAL",
    "2": "NEW",
    "3": "RANDOM",
    "4": "UNDISCLOSED"
  },
  "1085": {
    "0": "NONE",
    "1": "LOCAL",
    "2": "NATIONAL",
    "3": "GLOBAL"
  },
  "1093": {
    "1": "ODD_LOT",
    "2": "ROUND_LOT",
    "3": "BLOCK_LOT",
    "4": "ROUND_LOT_BASED_UPON_UNITOFMEASURE"
  },
  "1094": {
    "1": "LAST_PEG",
    "2": "MID_PRICE_PEG",
    "3": "OPENING_PEG",
    "4": "MARKET_PEG",
    "5": "PRIMARY_PEG",
    "7": "PEG_TO_VWAP",
    "8": "TRAILING_STOP_PEG",
    "9": "PEG_TO_LIMIT_PRICE"
  },
  "1095": {
    "1": "PARTIAL_EXECUTION",
    "2": "SPECIFIED_TRADING_SESSION",
    "3": "NEXT_AUCTION",
    "4": "PRICE_MOVEMENT"
  },
  "1101": {
    "1": "ACTIVATE",
    "2": "MODIFY",
    "3": "CANCEL"
  },
  "1102": {
    "1": "BEST_OFFER",
    "2": "LAST_TRADE",
    "3": "BEST_BID",
    "4": "BEST_BID_OR_LAST_TRADE",
    "5": "BEST_OFFER_OR_LAST_TRADE",
    "6": "BEST_MID"
  },
  "1108": {
    "0": "NONE",
    "1": "LOCAL",
    "2": "NATIONAL",
    "3": "GLOBAL"
  },
  "1109": {
    "U": "TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_UP_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE",
    "D": "TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_DOWN_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE"
  },
  "1110": {
    "1": "MARKET",
    "2": "LIMIT"
  },
  "1112": {
    "1": "ORDER",
    "2": "QUOTE",
    "3": "PRIVATELY_NEGOTIATED_TRADE",
    "4": "MULTILEG_ORDER",
    "5": "LINKED_ORDER",
    "6": "QUOTE_REQUEST",
    "7": "IMPLIED_ORDER",
    "8": "CROSS_ORDER",
    "9": "STREAMING_PRICE"
  },
  "1116": {
    "0": "TRADE_CONFIRMATION",
    "1": "TWO_PARTY_REPORT",
    "2": "ONE_PARTY_REPORT_FOR_MATCHING",
    "3": "ONE_PARTY_REPORT_FOR_PASS_THROUGH",
    "4": "AUTOMATED_FLOOR_ORDER_ROUTING",
    "5": "TWO_PARTY_REPORT_FOR_CLAIM"
  },
  "1124": {
    "0": "FIX27",
    "1": "FIX30",
    "2": "FIX40",
    "3": "FIX41",
    "4": "FIX42",
    "5": "FIX43",
    "6": "FIX44",
    "7": "FIX50",
    "8": "FIX50SP1",
    "9": "FIX50SP2"
  },
  "1129": {
    "B": "BIC",
    "C": "GENERALLY_ACCEPTED_MARKET_PARTICIPANT_IDENTIFIER",
    "D": "PROPRIETARY",
    "E": "ISO_COUNTRY_CODE",
    "G": "MIC"
  },
  "1134": {
    "0": "NOT_IMPLIED",
    "1": "IMPLIED_IN",
    "2": "IMPLIED_OUT",
    "3": "BOTH_IMPLIED_IN_AND_IMPLIED_OUT"
  },
  "1145": {
    "1": "PRELIMINARY",
    "2": "FINAL"
  },
  "1160": {
    "C": "CANCEL",
    "N": "NEW",
    "R": "REPLACE",
    "T": "RESTATE"
  },
  "1163": {
    "1": "INSTRUCTIONS_OF_BROKER",
    "2": "INSTRUCTIONS_FOR_INSTITUTION",
    "3": "INVESTOR"
  },
  "1165": {
    "0": "ACCEPTED",
    "5": "REJECTED",
    "6": "REMOVED_FROM_MARKET",
    "7": "EXPIRED",
    "12": "LOCKED_MARKET_WARNING",
    "13": "CROSS_MARKET_WARNING",
    "14": "CANCELED_DUE_TO_LOCK_MARKET",
    "15": "CANCELED_DUE_TO_CROSS_MARKET",
    "16": "ACTIVE"
  },
  "1168": {
    "1": "ALL_MARKET_PARTICIPANTS",
    "2": "SPECIFIED_MARKET_PARTICIPANTS",
    "3": "ALL_MARKET_MAKERS",
    "4": "PRIMARY_MARKET_MAKER"
  },
  "1173": {
    "1": "ORDER_IMBALANCE_AUCTION_IS_EXTENDED",
    "2": "TRADING_RESUMES",
    "3": "PRICE_VOLATILITY_INTERRUPTION",
    "4": "CHANGE_OF_TRADING_SESSION",
    "5": "CHANGE_OF_TRADING_SUBSESSION",
    "6": "CHANGE_OF_SECURITY_TRADING_STATUS",
    "7": "CHANGE_OF_BOOK_TYPE",
    "8": "CHANGE_OF_MARKET_DEPTH"
  },
  "1175": {
    "1": "EXCHANGE_LAST",
    "2": "HIGH",
    "3": "AVERAGE_PRICE",
    "4": "TURNOVER"
  },
  "1177": {
    "1": "CUSTOMER"
  },
  "1179": {
    "C": "CASH_SETTLEMENT_REQUIRED",
    "P": "PHYSICAL_SETTLEMENT_REQUIRED"
  },
  "1194": {
    "0": "EUROPEAN",
    "1": "AMERICAN",
    "2": "BERMUDA"
  },
  "1195": {
    "STD": "STANDARD",
    "INX": "INDEX",
    "INT": "INTEREST_RATE_INDEX",
    "PCTPAR": "PERCENT_OF_PAR"
  },
  "1197": {
    "EQTY": "PREMIUM_STYLE",
    "FUT": "FUTURES_STYLE_MARK_TO_MARKET",
    "FUTDA": "FUTURES_STYLE_WITH_AN_ATTACHED_CASH_ADJUSTMENT",
    "CDS": "CDS_STYLE_COLLATERALIZATION_OF_MARKET_TO_MARKET_AND_COUPON",
    "CDSD": "CDS_IN_DELIVERY"
  },
  "1198": {
    "0": "PRE_LISTED_ONLY",
    "1": "USER_REQUESTED"
  },
  "1199": {
    "0": "REGULAR",
    "1": "VARIABLE",
    "2": "FIXED",
    "3": "TRADED_AS_A_SPREAD_LEG",
    "4": "SETTLED_AS_A_SPREAD_LEG"
  },
  "1210": {
    "0": "MONTHS",
    "1": "DAYS",
    "2": "WEEKS",
    "3": "YEARS"
  },
  "1303": {
    "0": "YEARMONTH_ONLY",
    "1": "YEARMONTHDAY",
    "2": "YEARMONTHWEEK"
  },
  "1304": {
    "0": "PRICE",
    "1": "TICKS",
    "2": "PERCENTAGE"
  },
  "1307": {
    "0": "SYMBOL",
    "1": "SECURITYTYPE_AND_OR_CFICODE",
    "2": "PRODUCT",
    "3": "TRADINGSESSIONID",
    "4": "ALL_SECURITIES",
    "5": "UNDELYINGSYMBOL",
    "6": "UNDERLYING_SECURITYTYPE_AND_OR_CFICODE",
    "7": "UNDERLYING_PRODUCT",
    "8": "MARKETID_OR_MARKETID_PLUS_MARKETSEGMENTID"
  },
  "1308": {
    "0": "RETRANSMISSION_OF_APPLICATION_MESSAGES_FOR_THE_SPECIFIED_APPLICATIONS",
    "1": "SUBSCRIPTION_TO_THE_SPECIFIED_APPLICATIONS",
    "2": "REQUEST_FOR_THE_LAST_APPLLASTSEQNUM_PUBLISHED_FOR_THE_SPECIFIED_APPLICATIONS",
    "3": "REQUEST_VALID_SET_OF_APPLICATIONS",
    "4": "UNSUBSCRIBE_TO_THE_SPECIFIED_APPLICATIONS",
    "5": "CANCEL_RETRANSMISSION",
    "6": "CANCEL_RETRANSMISSION_AND_UNSUBSCRIBE_TO_THE_SPECIFIED_APPLICATIONS"
  },
  "1348": {
    "0": "REQUEST_SUCCESSFULLY_PROCESSED",
    "1": "APPLICATION_DOES_NOT_EXIST",
    "2": "MESSAGES_NOT_AVAILABLE"
  },
  "1349": {
    "0": "APPLICATION_DOES_NOT_EXIST",
    "1": "MESSAGES_REQUESTED_ARE_NOT_AVAILABLE",
    "2": "USER_NOT_AUTHORIZED_FOR_APPLICATION"
  },
  "1355": {
    "0": "TRADING_RESUMES",
    "1": "CHANGE_OF_TRADING_SESSION",
    "2": "CHANGE_OF_TRADING_SUBSESSION",
    "3": "CHANGE_OF_TRADING_STATUS"
  },
  "1369": {
    "1": "SUSPEND_ORDERS",
    "2": "RELEASE_ORDERS_FROM_SUSPENSION",
    "3": "CANCEL_ORDERS"
  },
  "1374": {
    "1": "ALL_ORDERS_FOR_A_SECURITY",
    "2": "ALL_ORDERS_FOR_AN_UNDERLYING_SECURITY",
    "3": "ALL_ORDERS_FOR_A_PRODUCT",
    "4": "ALL_ORDERS_FOR_A_CFICODE",
    "5": "ALL_ORDERS_FOR_A_SECURITYTYPE",
    "6": "ALL_ORDERS_FOR_A_TRADING_SESSION",
    "7": "ALL_ORDERS",
    "8": "ALL_ORDERS_FOR_A_MARKET",
    "9": "ALL_ORDERS_FOR_A_MARKET_SEGMENT",
    "10": "ALL_ORDERS_FOR_A_SECURITY_GROUP",
    "11": "CANCEL_FOR_SECURITY_ISSUER",
    "12": "CANCEL_FOR_ISSUER_OF_UNDERLYING_SECURITY"
  },
  "1375": {
    "0": "REJECTED",
    "1": "ACCEPTED"
  },
  "1376": {
    "0": "MASS_ACTION_NOT_SUPPORTED",
    "1": "INVALID_OR_UNKNOWN_SECURITY",
    "2": "INVALID_OR_UNKNOWN_UNDERLYING_SECURITY",
    "3": "INVALID_OR_UNKNOWN_PRODUCT",
    "4": "INVALID_OR_UNKNOWN_CFICODE",
    "5": "INVALID_OR_UNKNOWN_SECURITYTYPE",
    "6": "INVALID_OR_UNKNOWN_TRADING_SESSION",
    "7": "INVALID_OR_UNKNOWN_MARKET",
    "8": "INVALID_OR_UNKNOWN_MARKET_SEGMENT",
    "9": "INVALID_OR_UNKNOWN_SECURITY_GROUP",
    "10": "INVALID_OR_UNKNOWN_SECURITY_ISSUER",
    "11": "INVALID_OR_UNKNOWN_ISSUER_OF_UNDERLYING_SECURITY",
    "99": "OTHER"
  },
  "1377": {
    "0": "PREDEFINED_MULTILEG_SECURITY",
    "1": "USER_DEFINED_MULTLEG_SECURITY",
    "2": "USER_DEFINED_NON_SECURITIZED_MULTILEG"
  },
  "1378": {
    "0": "NET_PRICE",
    "1": "REVERSED_NET_PRICE",
    "2": "YIELD_DIFFERENCE",
    "3": "INDIVIDUAL",
    "4": "CONTRACT_WEIGHTED_AVERAGE_PRICE",
    "5": "MULTIPLIED_PRICE"
  },
  "1379": {
    "1": "ONE_CANCELS_THE_OTHER",
    "2": "ONE_TRIGGERS_THE_OTHER",
    "3": "ONE_UPDATES_THE_OTHER_3",
    "4": "ONE_UPDATES_THE_OTHER_4"
  },
  "1386": {
    "0": "BROKER",
    "2": "EXCHANGE_CLOSED",
    "4": "TOO_LATE_TO_ENTER",
    "5": "UNKNOWN_ORDER",
    "6": "DUPLICATE_ORDER",
    "11": "UNSUPPORTED_ORDER_CHARACTERISTIC",
    "99": "OTHER"
  },
  "1387": {
    "0": "DO_NOT_PUBLISH_TRADE",
    "1": "PUBLISH_TRADE",
    "2": "DEFERRED_PUBLICATION"
  },
  "1391": {
    "A": "ADD",
    "D": "DELETE",
    "M": "MODIFY"
  },
  "1396": {
    "0": "SESSION_ACTIVE",
    "1": "SESSION_PASSWORD_CHANGED",
    "2": "SESSION_PASSWORD_DUE_TO_EXPIRE",
    "3": "NEW_SESSION_PASSWORD_DOES_NOT_COMPLY_WITH_POLICY",
    "4": "SESSION_LOGOUT_COMPLETE",
    "5": "INVALID_USERNAME_OR_PASSWORD",
    "6": "ACCOUNT_LOCKED",
    "7": "LOGONS_ARE_NOT_ALLOWED_AT_THIS_TIME",
    "8": "PASSWORD_EXPIRED"
  },
  "1410": {
    "0": "RESET_APPLSEQNUM_TO_NEW_VALUE_SPECIFIED_IN_APPLNEWSEQNUM",
    "1": "REPORTS_THAT_THE_LAST_MESSAGE_HAS_BEEN_SENT_FOR_THE_APPLIDS_REFER_TO_REFAPPLLASTSEQNUM",
    "2": "HEARTBEAT_MESSAGE_INDICATING_THAT_APPLICATION_IDENTIFIED_BY_REFAPPLID",
    "3": "APPLICATION_MESSAGE_RE_SEND_COMPLETED"
  },
  "1427": {
    "0": "SECONDS",
    "1": "TENTHS_OF_A_SECOND",
    "2": "HUNDREDTHS_OF_A_SECOND",
    "3": "MILLISECONDS",
    "4": "MICROSECONDS",
    "5": "NANOSECONDS",
    "10": "MINUTES",
    "11": "HOURS",
    "12": "DAYS",
    "13": "WEEKS",
    "14": "MONTHS",
    "15": "YEARS"
  },
  "1430": {
    "E": "ELECTRONIC",
    "P": "PIT",
    "X": "EX_PIT"
  },
  "1431": {
    "0": "GTC_FROM_PREVIOUS_DAY",
    "1": "PARTIAL_FILL_REMAINING",
    "2": "ORDER_CHANGED"
  },
  "1432": {
    "1": "MEMBER_TRADING_FOR_THEIR_OWN_ACCOUNT",
    "2": "CLEARING_FIRM_TRADING_FOR_ITS_PROPRIETARY_ACCOUNT",
    "3": "MEMBER_TRADING_FOR_ANOTHER_MEMBER",
    "4": "ALL_OTHER"
  },
  "1433": {
    "0": "UTILITY_PROVIDED_STANDARD_MODEL",
    "1": "PROPRIETARY"
  },
  "1435": {
    "0": "SHARES",
    "1": "HOURS",
    "2": "DAYS"
  },
  "1436": {
    "0": "NERC_EASTERN_OFF_PEAK",
    "1": "NERC_WESTERN_OFF_PEAK",
    "2": "NERC_CALENDAR_ALL_DAYS_IN_MONTH",
    "3": "NERC_EASTERN_PEAK",
    "4": "NERC_WESTERN_PEAK"
  },
  "1440": {
    "0": "BLOOMBERG",
    "1": "REUTERS",
    "2": "TELERATE",
    "99": "OTHER"
  },
  "1447": {
    "0": "PRIMARY",
    "1": "SECONDARY"
  },
  "1448": {
    "FR": "FULL_RESTRUCTURING",
    "MR": "MODIFIED_RESTRUCTURING",
    "MM": "MODIFIED_MOD_RESTRUCTURING",
    "XR": "NO_RESTRUCTURING_SPECIFIED"
  },
  "1450": {
    "SD": "SENIOR_SECURED",
    "SR": "SENIOR",
    "SB": "SUBORDINATED"
  },
  "1451": {
    "1": "INDUSTRY_CLASSIFICATION",
    "2": "TRADING_LIST",
    "3": "MARKET",
    "4": "NEWSPAPER_LIST"
  },
  "1471": {
    "1": "ICB",
    "2": "NAICS",
    "3": "GICS"
  },
  "1472": {
    "0": "COMPANY_NEWS",
    "1": "MARKETPLACE_NEWS",
    "2": "FINANCIAL_MARKET_NEWS",
    "3": "TECHNICAL_NEWS",
    "99": "OTHER_NEWS"
  },
  "1474": {
    "0": "REPLACEMENT",
    "1": "OTHER_LANGUAGE",
    "2": "COMPLIMENTARY"
  },
  "1478": {
    "1": "FIXED_STRIKE",
    "2": "STRIKE_SET_AT_EXPIRATION_TO_UNDERLYING_OR_OTHER_VALUE",
    "3": "STRIKE_SET_TO_AVERAGE_OF_UNDERLYING_SETTLEMENT_PRICE_ACROSS_THE_LIFE_OF_THE_OPTION",
    "4": "STRIKE_SET_TO_OPTIMAL_VALUE"
  },
  "1479": {
    "1": "LESS_THAN_UNDERLYING_PRICE_IS_IN_THE_MONEY",
    "2": "LESS_THAN_OR_EQUAL_TO_THE_UNDERLYING_PRICE_IS_IN_THE_MONEY",
    "3": "EQUAL_TO_THE_UNDERLYING_PRICE_IS_IN_THE_MONEY",
    "4": "GREATER_THAN_OR_EQUAL_TO_UNDERLYING_PRICE_IS_IN_THE_MONEY",
    "5": "GREATER_THAN_UNDERLYING_IS_IN_THE_MONEY"
  },
  "1480": {
    "1": "REGULAR",
    "2": "SPECIAL_REFERENCE",
    "3": "OPTIMAL_VALUE",
    "4": "AVERAGE_VALUE"
  },
  "1482": {
    "1": "VANILLA",
    "2": "CAPPED",
    "3": "BINARY"
  },
  "1483": {
    "1": "CAPPED",
    "2": "TRIGGER",
    "3": "KNOCK_IN_UP",
    "4": "KOCK_IN_DOWN",
    "5": "KNOCK_OUT_UP",
    "6": "KNOCK_OUT_DOWN",
    "7": "UNDERLYING",
    "8": "RESET_BARRIER",
    "9": "ROLLING_BARRIER"
  },
  "1485": {
    "1": "LESS_THAN_COMPLEXEVENTPRICE",
    "2": "LESS_THAN_OR_EQUAL_TO_COMPLEXEVENTPRICE",
    "3": "EQUAL_TO_COMPLEXEVENTPRICE",
    "4": "GREATER_THAN_OR_EQUAL_TO_COMPLEXEVENTPRICE",
    "5": "GREATER_THAN_COMPLEXEVENTPRICE"
  },
  "1488": {
    "1": "EXPIRATION",
    "2": "IMMEDIATE",
    "3": "SPECIFIED_DATE_TIME"
  },
  "1490": {
    "1": "AND",
    "2": "OR"
  },
  "1491": {
    "1": "STREAM_ASSIGNMENT_FOR_NEW_CUSTOMER",
    "2": "STREAM_ASSIGNMENT_FOR_EXISTING_CUSTOMER"
  },
  "1499": {
    "0": "UNKNOWN_CLIENT",
    "1": "EXCEEDS_MAXIMUM_SIZE",
    "2": "UNKNOWN_OR_INVALID_CURRENCY_PAIR",
    "3": "NO_AVAILABLE_STREAM",
    "99": "OTHER"
  },
  "1503": {
    "0": "ASSIGNMENT_ACCEPTED",
    "1": "ASSIGNMENT_REJECTED"
  },
  "1504": {
    "0": "RETURN_ALL_AVAILABLE_INFORMATION_ON_PARTIES_AND_RELATED_PARTIES",
    "1": "RETURN_ONLY_PARTY_INFORMATION",
    "2": "INCLUDE_INFORMATION_ON_RELATED_PARTIES",
    "3": "INCLUDE_RISK_LIMIT_INFORMATION"
  },
  "1508": {
    "0": "VALID_REQUEST",
    "1": "INVALID_OR_UNSUPPORTED_REQUEST",
    "2": "NO_PARTIES_OR_PARTY_DETAILS_FOUND_THAT_MATCH_SELECTION_CRITERIA",
    "3": "UNSUPPORTED_PARTYLISTRESPONSETYPE",
    "4": "NOT_AUTHORIZED_TO_RETRIEVE_PARTIES_OR_PARTY_DETAILS_DATA",
    "5": "PARTIES_OR_PARTY_DETAILS_DATA_TEMPORARILY_UNAVAILABLE",
    "6": "REQUEST_FOR_PARTIES_DATA_NOT_SUPPORTED",
    "99": "OTHER"
  },
  "1512": {
    "0": "IS_ALSO",
    "1": "CLEARS_FOR",
    "2": "CLEARS_THROUGH",
    "3": "TRADES_FOR",
    "4": "TRADES_THROUGH",
    "5": "SPONSORS",
    "6": "SPONSORED_THROUGH",
    "7": "PROVIDES_GUARANTEE_FOR",
    "8": "IS_GUARANTEED_BY",
    "9": "MEMBER_OF",
    "10": "HAS_MEMBERS",
    "11": "PROVIDES_MARKETPLACE_FOR",
    "12": "PARTICIPANT_OF_MARKETPLACE",
    "13": "CARRIES_POSITIONS_FOR",
    "14": "POSTS_TRADES_TO",
    "15": "ENTERS_TRADES_FOR",
    "16": "ENTERS_TRADES_THROUGH",
    "17": "PROVIDES_QUOTES_TO",
    "18": "REQUESTS_QUOTES_FROM",
    "19": "INVESTS_FOR",
    "20": "INVESTS_THROUGH",
    "21": "BROKERS_TRADES_FOR",
    "22": "BROKERS_TRADES_THROUGH",
    "23": "PROVIDES_TRADING_SERVICES_FOR",
    "24": "USES_TRADING_SERVICES_OF",
    "25": "APPROVES_OF",
    "26": "APPROVED_BY",
    "27": "PARENT_FIRM_FOR",
    "28": "SUBSIDIARY_OF",
    "29": "REGULATORY_OWNER_OF",
    "30": "OWNED_BY_30",
    "31": "CONTROLS",
    "32": "IS_CONTROLLED_BY",
    "33": "LEGAL",
    "34": "OWNED_BY_34",
    "35": "BENEFICIAL_OWNER_OF",
    "36": "OWNED_BY_36"
  },
  "1516": {
    "1": "GROSS_LIMIT",
    "2": "NET_LIMIT",
    "3": "EXPOSURE",
    "4": "LONG_LIMIT",
    "5": "SHORT_LIMIT"
  },
  "1531": {
    "1": "INCLUDE",
    "2": "EXCLUDE"
  },
  "1536": {
    "1": "ASSIGNMENT",
    "2": "REJECTED",
    "3": "TERMINATE_UNASSIGN"
  }
};